### ISSUE TITLE
"Can't connect to server", incorrect chunk size | 1.16.5 support

### ISSUE THREAD

**Issue by SylveonBottle** [vincss/mcsleepingserverstarter#10]
```
2021-02-11 16:26:23.978 - info: A Prince has taken a quick peek. [handshaking_1.16.1]
Chunk size is 55 but only 3 was read ; partial packet : {"name":"legacy_server_list_ping","params":{"payload":1}}; buffer :fe0101fa000b004d0043007c00500069006e00670048005f0073007400197f0009006c006f00630061006c0068006f00730074000063dd
```
![image](https://user-images.githubusercontent.com/17802843/107700947-3117e880-6c86-11eb-9118-4fac69eae64e.png)
![image](https://user-images.githubusercontent.com/17802843/107701019-4db42080-6c86-11eb-8863-1a2f365939bf.png)

**Comment by vincss** [comment]
Hi !
Which version are you using ?
Node directly or a compiled one ?
Any way I made a new release, can you give it a try ?
Thanks.
https://github.com/vincss/mcsleepingserverstarter/releases/tag/1.16.4

**Comment by SylveonBottle** [comment]
New version works perfectly, thank you for releasing updated binaries.
