### ISSUE TITLE
Suggestion- Create an egg for the Pterodactyl Panel that has this built in

### ISSUE THREAD

**Issue by AJAYDEN55000** [vincss/mcsleepingserverstarter#100]
I use Pterodactyl panel and I don't currently see a way for this to work, is there any way you could make a pterodactyl panel egg that would have this built in?

**Comment by vincss** [comment]
There has been several Pterodactyl issue, but no one  wrote there solution in the wiki : 
https://github.com/vincss/mcsleepingserverstarter/issues/90

https://github.com/vincss/mcsleepingserverstarter/issues/88

So it's possible, but you got to figure out how, and write it in the wiki pages.

**Comment by BoredKevin** [comment]
I might release my pterodactyl egg soon™ 👀

**Comment by BoredKevin** [comment]
Just submitted a pull request and is waiting to be merged #107
