### ISSUE TITLE
Updated to 1.19 and server doesn't let me join in sleeping state.

### ISSUE THREAD

**Issue by Kingocharge** [vincss/mcsleepingserverstarter#101]
When the server is ''sleeping'' and i try to join, it says ''disconnected'' and in the console, this is the error message:

Chunk size is 832 but only 13 was read ; partial packet : {"name":"login_start","params":{"username":"KingoCharge"}}; buffer :000b4b696e676f43686172676501000001814a2acc90a60230820122300d06092a864886f70d01010105000382010f003082010a0282010100b3e7f4c7a8c037a40c7bf921423fe3ffbce470c4346742f658e5ffcb077cec7eeff11af2f117e855acd24e5103a11f1f9850cb361501787877bb89c469ab4ff240b15f6a8eef808f5a4c41b5547fa244727860ba8e1172d1c8d51d63d0f404bb431c11deccf68c7cd5cb1c1c370e96864dd5dcefda03d0d6bd356e1324e23d426f0cd8edbd308a7e8a2eb234bf8e85884529594bb1498645e2713255698929705c5e9c7eaee2dae5cf7f3289146154ed5515cd58a006c35ffbb708ba187dad4a82e052cd61ce155c8de1547528cf0d818dee2b6599631be3b3e0d6d137d7551a7bd7d76e5f4dd97f2031086a0ca71b69fe52be01cabf0314f26b6a465c6cbc6702030100018004c68d8df0b2a1a3e4af7fd4cc8d45ed5452f83634c27ea7b9f486f0ad0d559fff10e837d779e9eab32e00abde3f42553b7e9eb408683ce11b6e7cac366fa57ef09abbf992ba565f958103882fcd4cdbcf6cdb98d96cc08fb3c578557502847111e858cf638703dac03a44b41404b58dc24b0c4d2d4fe98bd6425c0814cf3fa6ebdc9de4893724841daa8d70000a7e6e25bde09b649a9af2c118d565d6efb5668f7344dadf2455ef190582a6dbf7f7bf3412ee97b803d27c9f831a3beda5960ee36fac02d867cba93a127c42971eddccdf2f58a2c4777efe5b79bdf83172face98f2e97a55c01a6445c6b3e6ee915c45252e715c58ea404131f5eb3f35a6b70e46bf9b54e2bd3ffd1c42121c4ac946dd430dfa4902912a09a5363317bbfccbadbc46f781e99978526b2899bb6b8bb949ab8f5d550eae6a545c3143e75ea00c94fb4c3ac21fe40cebd2b9d3661dde2ce7f850dac2e164232fda9594a73c1c116236aa29bee39f533a15aa1564315f22c4b1b5ae38fafcad50ca71e47cc4d6c175a03a72ca22e807a3fca447608256538c7d6d42b3e464ef30262dbdc271d5d8020e9ea2dc19e3340726e30b484b8dc5a0b78c6f3a4c5b241db8c70c3ead4f51850228ec0a560cd40eaa7305a4d731eab950ba6af35b18b7f0ccefa4144032c7917b9afb8a3f1cde898fb8d9ee57cae8d84fcc94e9c06ff30f63b2c057c243716926

**Comment by Kingocharge** [comment]
but when i turn on the spigot server normally i can jin without any issues.

**Comment by Kingocharge** [comment]
oh alright

**Comment by Kingocharge** [comment]
also do i have to update nodejs or anything else when it supports 1.19

**Comment by vincss** [comment]
No, you won't need any update (I don't think so :-D ).
You can also use the binary which are simpler to use.

**Comment by Kingocharge** [comment]
do i close the issue?

**Comment by vincss** [comment]
No it's fine, we will close it once it's compatible with 1.19, so anybody won't open another one.

**Comment by Kingocharge** [comment]
k

**Comment by Rysanlos** [comment]
You should maybe try to find another dependency? They take months to update to the newer protocol each time...

**Comment by vincss** [comment]
> You should maybe try to find another dependency? They take months to update to the newer protocol each time...

Do you have heard of any ?

**Comment by Rysanlos** [comment]
You can use this but it's in Java instead of node: https://github.com/GeyserMC/MCProtocolLib

**Comment by vincss** [comment]
There is a first version with a WIP version of the minecraft-protocol :
https://github.com/vincss/mcsleepingserverstarter/actions/runs/2740226640

branch : https://github.com/vincss/mcsleepingserverstarter/tree/feature/version_1.19

**Comment by Rysanlos** [comment]
To make things easier, we should be able to wake the server regardless the Minecraft version we use?

**Comment by vincss** [comment]
Yes it would be great, but the protocol used by minecraft is not always the same between versions.
You can always use the web interface.

**Comment by PandaUprising** [comment]
So is there any way to us mcsleepingserverstarter right now or do we just need to wait?

**Comment by vincss** [comment]
> So is there any way to use mcsleepingserverstarter right now or do we just need to wait?

Yes with the web interface.

**Comment by PandaUprising** [comment]
OK thanks!

**Comment by vincss** [comment]
Hi ! 
There is a beta version for the 1.19 ( not yet the 1.92.2 ) 
https://github.com/vincss/mcsleepingserverstarter/tree/feature/version_1.19

https://github.com/vincss/mcsleepingserverstarter/actions/runs/2823672117

**Comment by VikingLord501st** [comment]
Thanks for sharing the link, can I drag and drop the new files and just "replace all"?

**Comment by vincss** [comment]
Can you share the console log (add a pause at the end of your bat) ? 
Are you using the binary ?
Are you using 1.19 (and NOT 1.19.1 or 1.19.2) ?

**Comment by VikingLord501st** [comment]
The server is working on 1.19, when I start up the server by clicking on the .bat, it goes through these scripts:
> mcsleepingserverstarter@1.2.0 start
> npm run prebuild && npm run build:typescript && node .


> mcsleepingserverstarter@1.2.0 prebuild
> rimraf ./build/ ./bin/ && cpx-fixed "views/**/*.*" build/views


> mcsleepingserverstarter@1.2.0 build:typescript
> tsc"

Then shutdowns without any warning, I can just about see a paragraph of words which I supose is the usual startup code but then disappears. I took a screen recording and paused it at the right moment to show that code. It is not the usual start up code. Since I am terrible at coding I will pass you on the screen shot of 0.000009 seconds before it closes the program

![Screenshot (573)](https://user-images.githubusercontent.com/111013084/184019998-ee5ddcbd-0c47-40fa-b69d-6e6af231bb9d.png)
.

**Comment by vincss** [comment]
You can do a execute the following command in your folder 
 npm ci
Or you can try with the binary

**Comment by VikingLord501st** [comment]
npm ci in the commands.yml folder?

**Comment by vincss** [comment]
At the root where you extracted your files. But I think you should go for the binary.

**Comment by VikingLord501st** [comment]
I'm not quite sure what you mean, I extracted my files it the main server file thing, I am not this good a tech so you will have to explain where the binary is..... I'm sorry
![Screenshot (578)](https://user-images.githubusercontent.com/111013084/184145104-302dff3a-fc6b-48a9-99bd-528042e1ea17.png)
.

**Comment by vincss** [comment]
You can replace everything you downloaded from the github, and use the binary contained in this zip : 
https://github.com/vincss/mcsleepingserverstarter/suites/7728543132/artifacts/323939792

**Comment by VikingLord501st** [comment]
Okay, thanks so much vincss, it worked. Everything is working now.

**Comment by PandaUprising** [comment]
Yes works thank you very much!!!

**Comment by vincss** [comment]
The release on the minecraft-protocol side has been made, for I also made the one for SSS : 
https://github.com/vincss/mcsleepingserverstarter/releases

**Comment by Rysanlos** [comment]
> > You should maybe try to find another dependency? They take months to update to the newer protocol each time...
> 
> Do you have heard of any other?

I found this
https://github.com/barneygale/quarry

**Comment by vincss** [comment]
> > > You should maybe try to find another dependency? They take months to update to the newer protocol each time...
> > 
> > 
> > Do you have heard of any other?
> 
> I found this https://github.com/barneygale/quarry

Hi !
Thanks for the research, but unfortunately it's for Python, SSS is written in Node.
