### ISSUE TITLE
Be able to put web start on a subdirectory of the website

### ISSUE THREAD

**Issue by DUCKONAROLL** [vincss/mcsleepingserverstarter#102]
Like the title says, lets say google decides to open a Minecraft server or something and they could put it on google.com/startminecraftserver instead of having to replace google.com, if there is already a way to do this please let me know

**Comment by vincss** [comment]
Currently there is not, because the API server and the web server is running inside MC SSS.

**Comment by DUCKONAROLL** [comment]
I know it's been a while, but I think I have the answer, as long as this works how I think this works.

My server has been long dead, so I haven't had the chance to test the sleeping webserver with this, but while setting up [Wetty](https://github.com/butlerx/wetty), I noticed how broad the instructions to use it with Nginx were: https://github.com/butlerx/wetty/blob/main/docs/nginx.md

I'm pretty sure changing that localhost:3000 block of code to simply reflect the sleeping server's port and changing the location line at the top to not direct to /wetty but instead to /minecraftserver or something could show the web activate screen in a subdirectory. It seems to be a little more complex for Apache, though. Regardless, it's a good start.

**Comment by vincss** [comment]
Yes, you can do some redirections in nginx.
If you succeed write it to a wiki page. ;-)

**Comment by markmetcalfe** [comment]
Have created #154 which solves this

**Comment by markmetcalfe** [comment]
@vincss this issue can be closed now

**Comment by vincss** [comment]
Yes it can, thank you. Don't forget the wiki please. ;-)

**Comment by markmetcalfe** [comment]
> Yes it can, thank you. Don't forget the wiki please. ;-)

[I've added a wiki page here](https://github.com/vincss/mcsleepingserverstarter/wiki/NGINX-Reverse-Proxy-Setup) 😃
