### ISSUE TITLE
4 high severity vurnabilities?

### ISSUE THREAD

**Issue by warior456** [vincss/mcsleepingserverstarter#106]

**Comment by vincss** [comment]
Hi !
Yes, it's on a dependency for bedrock : 
https://github.com/JSPrismarine/JSPrismarine/issues/701

**Comment by PandaUprising** [comment]
I am getting the same, how to fix?

**Comment by vincss** [comment]
We need a new release, see the previous comment.

**Comment by PandaUprising** [comment]
Ahh ok np

**Comment by filiphsps** [comment]
https://github.com/JSPrismarine/JSPrismarine/issues/701#issuecomment-1681558000 this isn’t properly tested outside of the automated tests we’ve setup so YMMV, but whoop whoop 🤠

Let me know if it crashes and burns, otherwise I’ll have to get back to working on @NordcomInc 😅
