### ISSUE TITLE
Change Sleeping-State Server Icon?

### ISSUE THREAD

**Issue by d1ddle** [vincss/mcsleepingserverstarter#11]
I'm happy to report it works great on 1.16.5!
However I'm not sure if I'm being dense or this is actually an issue but, on 1.16.5, the sleeping-state server icon doesn't update when I change server-icon.png in the server root. Is it pointed to somewhere else? I'm not too educated on the subject.
It might be because I have the Windows .exe pointed to from a Windows Service, but I'm not sure that has any effect on this.
I'll try to uninstall the service and re-install to see if changing the server-icon worked. I'll report back the results, of course.
Any comments are appreciated!

**Comment by vincss** [comment]
Hi !
For now, it's hardcoded image/png;base64 in the server, line 3, and used at line 90. 
https://github.com/vincss/mcsleepingserverstarter/blob/master/sleepingServerStarter.js#L90

You can generate your own image base64 using an online service : https://www.base64-image.de/ 
Then replace it in the code. But then you need to run it from node/npm not the bundled .exe.

**Comment by d1ddle** [comment]
Hi, thanks for the reply. Would there be any way I could, recompile the binary, just for simplicity in terms of keeping it running as a Windows service?

**Comment by vincss** [comment]
You can run the commands :
```
npm i
npm run build:win
```
Then the binary will be available in : ./bin .

**Comment by d1ddle** [comment]
Thanks! Works fantastic! I'm chuffed.
