### ISSUE TITLE
Syntax error: Unterminated quoted string when running in pterodactyl

### ISSUE THREAD

**Issue by NoSadBeHappy** [vincss/mcsleepingserverstarter#110]
I installed the egg provided for pterodactyl for use with paper servers. after installing an instance, I got this error message when trying to start the server.

`container@pterodactyl~ ./mcsleepingserverstarter-linux
./mcsleepingserverstarter-linux: 2: Syntax error: Unterminated quoted string`

**Comment by vincss** [comment]
Hi !
@BoredKevin , any ideas ?

**Comment by BoredKevin** [comment]
Hello, I was not able to re-create this error. Can you tell me what you did and the steps to re-create this error?

**Comment by NoSadBeHappy** [comment]
Of course! 

I am on pterodactyl version 1.10.1

I downloaded the json file from the readme of this project.
Added it as a new egg inside the "Minecraft" nest, without changing any settings.
I started a new server, using that egg, with the following settings changed

- changed node to the same node as the server that I want mcsleepingserverstarter to control, and gave it a new port.
- set memory to 512 mb
- gave it unlimited disk space (set value to 0)

After it installed for a bit, it automatically tried to start, and this is the console output I got.


`container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from pterodactyl/yolks 
Status: Image is up to date for ghcr.io/pterodactyl/yolks:java_17 
Digest: sha256:46d8163f4493460caa607d65dbb665f76ed28add67594f8cd75bb5ad6fb4aa93 
[Pterodactyl Daemon]: Finished pulling Docker container image
container@pterodactyl~ java -version
openjdk version "17.0.2" 2022-01-18
OpenJDK Runtime Environment (build 17.0.2+8-86)
OpenJDK 64-Bit Server VM (build 17.0.2+8-86, mixed mode, sharing)
container@pterodactyl~ ./mcsleepingserverstarter-linux
./mcsleepingserverstarter-linux: 2: Syntax error: Unterminated quoted string
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 2
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from pterodactyl/yolks 
Status: Image is up to date for ghcr.io/pterodactyl/yolks:java_17 
Digest: sha256:46d8163f4493460caa607d65dbb665f76ed28add67594f8cd75bb5ad6fb4aa93 
[Pterodactyl Daemon]: Finished pulling Docker container image
container@pterodactyl~ java -version
openjdk version "17.0.2" 2022-01-18
OpenJDK Runtime Environment (build 17.0.2+8-86)
OpenJDK 64-Bit Server VM (build 17.0.2+8-86, mixed mode, sharing)
container@pterodactyl~ ./mcsleepingserverstarter-linux
./mcsleepingserverstarter-linux: 2: Syntax error: Unterminated quoted string
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 2
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago.`

**Comment by NoSadBeHappy** [comment]
![image](https://user-images.githubusercontent.com/95050434/183508909-897d597e-8de4-47cb-8c03-de57ce19abe8.png)


Here is a screenshot of the console, as copying and pasting made a mess.

**Comment by BoredKevin** [comment]
Hi! Can you give me the logs of the installation process? It seems as your executable may be corrupted. A temporary fix you can do is by uploading your own executable from the GitHub releases

**Comment by NoSadBeHappy** [comment]
Hello!

Where are the installation logs located? I tried to upload the executable from github releases, and now when I try to start the server it says permission denied. So I tried to do `chmod +x mcsleepingserverstarter-linux` but I cant get into the folder because of a permission error.

**Comment by BoredKevin** [comment]
Hi! I've updated the egg so it does the `chmod +x mcsleepingserverstarter-linux` command when you reinstall the server, can you try that?

**Comment by vincss** [comment]
No news, I will close it.
