### ISSUE TITLE
Importing Egg Failure

### ISSUE THREAD

**Issue by slymerog** [vincss/mcsleepingserverstarter#111]
Hi,

I'm using Wisp, and I know that the Egg was stated for the open source version of the panel but of them being literally the same thing, figured I'd give it a shot. The Vanilla Egg imported with out a problem, but the Paper Egg is the one I need sadly! Every time I try to import it, I get this error saying "_Something went wrong while trying to perform this action_."

I checked the logs, but I don't see any errors pertaining to this issue, besides the loads of crap from other things...
https://pastebin.com/DKT75r8z

Thanks!

**Comment by vincss** [comment]
Hi,
Did you mange to solve this ?
