### ISSUE TITLE
Joining on different versions

### ISSUE THREAD

**Issue by PandaUprising** [vincss/mcsleepingserverstarter#114]
I was just wondering when joining the server in sleeping mode, say... mcsleepingserverstarter was configured on 1.19 but you want to join on 1.19.2 is there a way for it to allow connections from different versions?

Thanks, PandaUprising

**Comment by vincss** [comment]
Hi !
For now 1.19.2 is not supported yet, but anyway multiple versions are not supported, you can use the web-interface if you want to wake it up.
