### ISSUE TITLE
Problems installing plugin on Ubuntu 22.04.1 server

### ISSUE THREAD

**Issue by wiXterTheGuy** [vincss/mcsleepingserverstarter#115]
I have some problems installing MCSleepingServerStarter on my Ubuntu system, command "chmod +x mcsleepingserverstarter-linux" doesnt do anything.

**Comment by vincss** [comment]
How did you install it ?
This command is meant for the binary files.

**Comment by wiXterTheGuy** [comment]
I moved the file mcsleepingserverstarter-linux using WinSCP to folder with server files and ran this command

**Comment by vincss** [comment]
This command only aim to make the mcsleepingserverstarter-linux file executable.
You can check it using : 
ls -l
Then you should be able to run it with : 
./mcsleepingserverstarter-linux

Hope it helps.

**Comment by wiXterTheGuy** [comment]
It works thanks!

**Comment by wiXterTheGuy** [comment]
Im closing it
