### ISSUE TITLE
Missing version 1.19.2

### ISSUE THREAD

**Issue by wiXterTheGuy** [vincss/mcsleepingserverstarter#116]
Does this plugin support 1.19.2? I ve set this version in the sleppingSettings.yml, but it shows 1.19 in the game and i cant join from 1.19.2. If it is only for 1.19 i will have to change the version of the server.

**Comment by vincss** [comment]
Hi, it doesn't support 1.19.2 for now 
https://github.com/vincss/mcsleepingserverstarter/issues/114#issuecomment-1225681671
We are waiting for a new version of the protocol : 
https://github.com/PrismarineJS/node-minecraft-protocol

**Comment by wiXterTheGuy** [comment]
Ok, I will just wait. What will be the best method to update this plugin? Will i have to delete all of its files and install the new ones?

**Comment by vincss** [comment]
Just replace the executable when its released

**Comment by wiXterTheGuy** [comment]
Ok thank you for support!
