### ISSUE TITLE
Can't type commands on Paper 1.19.2 server

### ISSUE THREAD

**Issue by iCrazyBlaze** [vincss/mcsleepingserverstarter#118]
I'm currently running a server with Paper 1.19.2, Sleeping Server Starter works great until i type a command. Typing commands like "list" or "help" doesn't produce an output, and shortly after the input is entirely disabled and i can't issue any other commands.

**Comment by iCrazyBlaze** [comment]
I am getting around this issue for now by using RCON to manage the server's commands

**Comment by vincss** [comment]
Hi !
"Something bad happened. bind EACCES 0.0.0.0:19132"
This means you have something already running on port 19132.
Can you give the full settings that you are using ?
