### ISSUE TITLE
Players joining on 1.19.2 cause an error - can only start from web

### ISSUE THREAD

**Issue by iCrazyBlaze** [vincss/mcsleepingserverstarter#119]
Logs here: https://pastebin.com/7eyjN7ty

**Comment by vincss** [comment]
Hi !
We need to wait for a new release of the minecraft-protocol package to be compatible with 1.19.2: 
https://github.com/PrismarineJS/node-minecraft-protocol

**Comment by MattJGH** [comment]
> Hi ! We need to wait for a new release of the minecraft-protocol package to be compatible with 1.19.2: https://github.com/PrismarineJS/node-minecraft-protocol

There is a test version with 1.19 support in the repo. Does that mean this tool can be updated?

**Comment by vincss** [comment]
It's should be working for 1.19 but not 1.19.2 .

**Comment by vincss** [comment]
Hi !
Support for 1.19.2 is out (no 1.19.3 yet) :
https://github.com/vincss/mcsleepingserverstarter/releases/tag/v1.2.4
