### ISSUE TITLE
Can't Start mcsleepingserverstarter

### ISSUE THREAD

**Issue by MrPresidentWhite** [vincss/mcsleepingserverstarter#12]
Hi, i have an issue when i'm executing the command `npm start`

![Screenshot_549](https://user-images.githubusercontent.com/38688739/109216926-71628500-77b5-11eb-8a4d-07f45e998812.png)

i have also attached the npm log

[2021-02-25T21_04_13_837Z-debug.log](https://github.com/vincss/mcsleepingserverstarter/files/6045762/2021-02-25T21_04_13_837Z-debug.log)

i hope you can help me with this issue

**Comment by vincss** [comment]
Did you do a 'npm i' before npm start ? Which version of node are you using ?

**Comment by MrPresidentWhite** [comment]
yes i executed npm install an i'm using the node version 10.23.1

**Comment by vincss** [comment]
Can you run this command and check the versions that you are using ?
`$ npm list yggdrasil
mcsleepingserverstarter@1.16.4 ****
`-- minecraft-protocol@1.23.1
  `-- yggdrasil@1.5.2
`

**Comment by MrPresidentWhite** [comment]
I'm sorry for the late reply.  I will test it out this afternoon (German time).  Unfortunately I don't have time at the moment.  I will then contact you again.

**Comment by MrPresidentWhite** [comment]
hello again, i have tested it with node 14 and this worked. thank you for your help.

**Comment by vincss** [comment]
Thanks for reporting this issue, I updated the doc.
