### ISSUE TITLE
Executable error

### ISSUE THREAD

**Issue by PandaUprising** [vincss/mcsleepingserverstarter#123]
Hey vincss!

Just here to let you know that there is an error in the executable file. It says v 1.2.0 while the actual version is 1.2.1

<img width="371" alt="image" src="https://user-images.githubusercontent.com/110600797/192273486-c3160f86-e082-4220-989d-c76665704a4b.png">

Hope your going well!

**Comment by vincss** [comment]
Hi !
Indeed, I will try to keep that aligned for the next versions.

**Comment by PandaUprising** [comment]
No problem,

Hope you have a wonderful day!
