### ISSUE TITLE
Pterodactyl Install Script with Paper/Spigot

### ISSUE THREAD

**Issue by Timongcraft** [vincss/mcsleepingserverstarter#124]
Hello, If I install/reinstall on my panel a server using the newest version of the egg (paper) it generates a file with a strange name. Can someone test it if its is only an issue one my site or with the egg. And the file regenerates every time I delete it.

**Comment by vincss** [comment]
Can you paste the strange name you are talking about ? 
@BoredKevin any ideas ?
I still don't have a Pterodactyl setup to test it.

**Comment by Timong-craft** [comment]
The Console
![image](https://user-images.githubusercontent.com/77288029/195864280-cfe5527e-30a9-4a25-9946-b4ef3ec01647.png)
And here the File: "���@���@8@@@@@@��@@@@LLL���H�HД���������"
![image](https://user-images.githubusercontent.com/77288029/195864440-a6f9dfd1-513b-4f0c-bf7e-17d33465692f.png)

**Comment by vincss** [comment]
I've tested on several regular linux installation and it's working. 
Maybe it's got something to do with the container used in Pterodactyl.

How did you installed it (Pterodactyl) ?

**Comment by Timong-craft** [comment]
Via the unofficial install script "https://github.com/vilhelmprytz/pterodactyl-installer"

**Comment by vincss** [comment]
Hi !
I finally toke the time to install it (thanks to your script ;-) ) :
But everything seems fine on my side :
![image](https://user-images.githubusercontent.com/2254806/196134451-ce33bed3-6dac-4384-ae99-1604027a34be.png)

![image](https://user-images.githubusercontent.com/2254806/196134285-0880488e-7a4b-4087-99f3-6451bc9c1e10.png)

Did you try a fresh start? Maybe the binary downloaded has been corrupted at some point ?

**Comment by vincss** [comment]
@BoredKevin , shouldn't we have a server.jar file ?

**Comment by BoredKevin** [comment]
> @BoredKevin , shouldn't we have a server.jar file ?

Hi, sorry for being absent over the last few weeks, I've been busy. I've tried it on my end and the results are fine, from the original screenshots I can see that where the script was supposed to be writing to the server.jar file, it was writing to the name instead. Are you sure your pterodactyl instance is up-to-date? @Timong-craft

**Comment by Timong-craft** [comment]
My panel is up to date but as I said it is likely because of oracle

**Comment by vincss** [comment]
Any news on this one ? I closed it, you can re-open it if we can do something on our side.

**Comment by Timong-craft** [comment]
No, it worked on my old panel but as I said I think its because of oracle and not you but thanks.
