### ISSUE TITLE
Get "Invalid Signature" When using this with Paper 1.19.2

### ISSUE THREAD

**Issue by DebugDax** [vincss/mcsleepingserverstarter#125]
Hello,

I use paper-1.19.2 and my server runs fine when started normally. When I use this tool (in the same folder as the server JAR), I can see the server sleeping in server list in-game, but when I join, it throws an "Invalid Signature for profile public key".

This only happens when using your utility and trying to join the sleeping server to wake it up. If I just join my server normally this error does not appear. I have restarted my client as the error displays and it does not resolve when using the sleeping starter.

Via various searching online I saw that changing "enforce-secure-profile=false" in server.properties, but that did not resolve this issue.

sleepingSettings.yml

serverName: Frozen Comet, waiting to thaw...

serverPort: 25565

bedrockPort: 

maxPlayers: 5

loginMessage: ...Heating up the Comet, Check back in a minute...

serverOnlineMode: true

webPort: 0

webStopOnStart: false

startMinecraft: true

minecraftCommand: java -Xms6G -Xmx10G -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true -jar paper-1.19.2-213.jar --nogui

--

Console message when trying to wake up server on join:
![image](https://user-images.githubusercontent.com/6743505/197012523-afe85b96-fdfe-4326-b9e3-8608122f2fe1.png)

in-game message:
![image](https://user-images.githubusercontent.com/6743505/197012697-39d6af29-00c5-449e-ac61-17c6f99d01b6.png)

**Comment by vincss** [comment]
Hi !
Thanks for the well documented issue.
Unfortunately the library on which this app is based is not yet compatible with MC 1.19.2 :
https://github.com/PrismarineJS/node-minecraft-protocol
https://github.com/vincss/mcsleepingserverstarter/issues/119

**Comment by Rysanlos** [comment]
With this error we should be able to trigger the wake for the server right? Sure the error is ugly but the script is detecting player activity.

**Comment by vincss** [comment]
> 
Unfortunately, it's an internal error in the minecraft-protocol library, and don't have any notifications or events for this one. :(

**Comment by Rysanlos** [comment]
> > 
> 
> Unfortunately, it's an internal error in the minecraft-protocol library, and don't have any notifications or events for this one. :(

On the latest Release 1.36.2 that came out today, they added ''Throw error on minecraft-data protocol version mismatch''
This could do the trick?

**Comment by zase414** [comment]
Will the issue be solved when I eventually download a compatible updated binary and run it in the place of the old one? (using ARM64 RPi, also I'm new to linux so sorry if this is a stupid question)

**Comment by vincss** [comment]
Hi !
Support for 1.19.2 is out (no 1.19.3 yet) :
https://github.com/vincss/mcsleepingserverstarter/releases/tag/v1.2.4

**Comment by alt162** [comment]
Attempting to run v1.2.4 and I'm getting a syntax error after running npm start. Not sure if this should be a separate issue thread... 
![syntaxerror](https://user-images.githubusercontent.com/122834883/212769641-6c5d10fa-fb5b-48e8-9132-5e75c92fa4f2.PNG)

**Comment by vincss** [comment]
Did you do a 'npm ci' before running start ?

**Comment by alt162** [comment]
Ran the binary without issue. A bit new to this. Thanks for this tool!
