### ISSUE TITLE
1.19.4 not compatible 

### ISSUE THREAD

**Issue by dewyi** [vincss/mcsleepingserverstarter#128]
Internal Exception: io.netty.handler.codec.DecoderException: net.minecraft.class_151: Non [a-z0-9_.-] character in namespace of location: {"text":"... Waking server up, come back in a minute..."}

![2022-11-23_21 37 05](https://user-images.githubusercontent.com/88068516/203561331-530c9a22-78fb-4554-957e-fae43c03dc7c.png)

No error logs in client logs nor server logs, only in minecraft. The server starts normally.

sleepingSettings.yml:

> serverName: Server sleeping, join to wake up
serverPort: 25565
bedrockPort: 0
maxPlayers: 69
loginMessage: ...Waking server up, come back in a minute...
serverOnlineMode: false
webPort: 8080
webStopOnStart: false
startMinecraft: true
minecraftCommand: java -Xmx2G -Xms2G -XX:+UnlockExperimentalVMOptions -XX:+UnlockDiagnosticVMOptions -XX:+AlwaysActAsServerClassMachine -XX:+AlwaysPreTouch -XX:+DisableExplicitGC -XX:+UseNUMA -XX:NmethodSweepActivity=1 -XX:ReservedCodeCacheSize=400M -XX:NonNMethodCodeHeapSize=12M -XX:ProfiledCodeHeapSize=194M -XX:NonProfiledCodeHeapSize=194M -XX:-DontCompileHugeMethods -XX:MaxNodeLimit=240000 -XX:NodeLimitFudgeFactor=8000 -XX:+UseVectorCmov -XX:+PerfDisableSharedMem -XX:+UseFastUnorderedTimeStamps -XX:+UseCriticalJavaThreadPriority -XX:ThreadPriorityPolicy=1 -XX:AllocatePrefetchStyle=3 -XX:+UseG1GC -XX:MaxGCPauseMillis=130 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=28 -XX:G1HeapRegionSize=16M -XX:G1ReservePercent=20 -XX:G1MixedGCCountTarget=3 -XX:InitiatingHeapOccupancyPercent=10 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=0 -XX:SurvivorRatio=32 -XX:MaxTenuringThreshold=1 -XX:G1SATBBufferEnqueueingThresholdPercent=30 -XX:G1ConcMarkStepDurationMillis=5 -XX:G1ConcRSHotCardLimit=16 -XX:G1ConcRefinementServiceIntervalMillis=150 --add-modules=jdk.incubator.vector -jar purpur-1.19.2-1845.jar

**Client**
OS: Linux 6.0.8-1-MANJARO x86_64 GNU/Linux
Java: java 17.0.5 2022-10-18 LTS
Java(TM) SE Runtime Environment GraalVM EE 22.3.0 (build 17.0.5+9-LTS-jvmci-22.3-b07)
Java HotSpot(TM) 64-Bit Server VM GraalVM EE 22.3.0 (build 17.0.5+9-LTS-jvmci-22.3-b07, mixed mode, sharing)

**Server**
OS?: Linux 4.14.113-25257816 aarch64 Android -- maybe running on android is bad
running on ubuntu 20.04.5 prooted environment
Java: openjdk 17.0.5 2022-10-18
OpenJDK Runtime Environment (build 17.0.5+8-Ubuntu-2ubuntu120.04)
OpenJDK 64-Bit Server VM (build 17.0.5+8-Ubuntu-2ubuntu120.04, mixed mode, sharing)

**Comment by vincss** [comment]
Hi !
Do you have carriage return in the original .yml file ?
Yml format heavily rely on indentation.

**Comment by dewyi** [comment]
No, originally there wasn't

**Comment by dewyi** [comment]
I will try re-generating the .yml file.

**Comment by dewyi** [comment]
Oh, there was. Sorry the .yml file I copied and pasted displays it wrongly

**Comment by vincss** [comment]
Which version of minecraft are you using ? 1.19.2 offline ?

**Comment by dewyi** [comment]
> Which version of minecraft are you using ? 1.19.2 offline ?

1.19.2 premium on multimc

**Comment by vincss** [comment]
It's still not compatible with 1.19.2 as said in many other issues.

**Comment by vincss** [comment]
Hi !
Support for 1.19.2 is out (no 1.19.3 yet) :
https://github.com/vincss/mcsleepingserverstarter/releases/tag/v1.2.4

**Comment by dewyi** [comment]
> Hi !
> Support for 1.19.2 is out (no 1.19.3 yet) :
> https://github.com/vincss/mcsleepingserverstarter/releases/tag/v1.2.4

Thank you!

**Comment by canthisbe** [comment]
This issue is still present today, even when deleting the yml and regenerating it.
![image](https://user-images.githubusercontent.com/85720328/230257588-46e38a8b-c569-422a-8544-460a81ac2d68.png)

**Comment by vincss** [comment]
Which minecraft version did you use ?

**Comment by canthisbe** [comment]
> Which minecraft version did you use ?

1.19.4

**Comment by vincss** [comment]
1.19.4 is not compatible yet

**Comment by Mutex01** [comment]
Is there anything we could help with? Would really love to use this with 1.19.4 :)

**Comment by vincss** [comment]
You can make a PR on https://github.com/PrismarineJS/node-minecraft-protocol
No ETA, sorry, it doesn't depend on me.

**Comment by vincss** [comment]
https://github.com/vincss/mcsleepingserverstarter/releases/tag/v1.5.11
