### ISSUE TITLE
How to install on Docker Minecraft Server?

### ISSUE THREAD

**Issue by noomis** [vincss/mcsleepingserverstarter#129]
Hi, i would like to install it on my 1.19.2 Minecraft Server which is running as a docker container on my unraid server.
Is it compatible on that?
If so can u give me a short explanation how to set this up on a docker container?

**Comment by vincss** [comment]
Hi !
Currently 1.19.2 is not compatible :
https://github.com/vincss/mcsleepingserverstarter/issues/125
https://github.com/vincss/mcsleepingserverstarter/issues/119

For docker installation, I think the easiest way is to use Pufferpnal or Pterodactyl.
https://github.com/vincss/mcsleepingserverstarter#-pufferpanel

**Comment by Jannik44** [comment]
hi, i did it inside a docker container and it worked quite well, took only a while to set it up

**Comment by vincss** [comment]
Hi @Jannik44 ,
Can you tell us a bit more on how did you do ? 
Maybe create an entry in the wiki :
https://github.com/vincss/mcsleepingserverstarter/wiki

**Comment by noomis** [comment]
Which Version of Minecraft is ur Server running? :)

**Comment by Jannik44** [comment]
> Hi @Jannik44 ,
> Can you tell us a bit more on how did you do ? 
> Maybe create an entry in the wiki :
> https://github.com/vincss/mcsleepingserverstarter/wiki


give me a few more days, i will update it and add a few more firewall rules, will publish it after that, will be like a plug and play version of your code combined with a few other useful things

**Comment by Jannik44** [comment]
> Which Version of Minecraft is ur Server running? :)

my server runs on 1.19.2 it works but if you run it higher than 1.19 it will show an error instead of the join message
