### ISSUE TITLE
Feature Request : Block ip

### ISSUE THREAD

**Issue by Jannik44** [vincss/mcsleepingserverstarter#132]
Hello, i have the problem that my mc server starts every two hours because of some kind of minecraft server scanner, i figured out its ip adress so it would be really cool to have settings in the config file to block traffic from specific ip adresses

**Comment by vincss** [comment]
Hi !
It could be helpful indeed, I will have a look.

**Comment by vincss** [comment]
Hi !
First of all, did you change the default port for your server ? It could be useful to prevent port scanning.

I added a parameter on a branch : 
https://github.com/vincss/mcsleepingserverstarter/pull/136/files?short_path=b335630#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5

https://github.com/vincss/mcsleepingserverstarter/tree/feature/blackListedAddress

Binaries : 
https://github.com/vincss/mcsleepingserverstarter/actions/runs/3931160441

Can you give it a try and tell me if it fits your needs ?

**Comment by Jannik44** [comment]
> Hi ! First of all, did you change the default port for your server ? It could be useful to prevent port scanning.
> 
> I added a parameter on a branch : https://github.com/vincss/mcsleepingserverstarter/pull/136/files?short_path=b335630#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5
> 
> https://github.com/vincss/mcsleepingserverstarter/tree/feature/blackListedAddress
> 
> Binaries : https://github.com/vincss/mcsleepingserverstarter/actions/runs/3931160441
> 
> Can you give it a try and tell me if it fits your needs ?

nah, i prefer the default port, but i will maybe just use SRV records in the future

the blacklist parameter looks promising :eyes: 

btw. this returns a 404
https://github.com/vincss/mcsleepingserverstarter/tree/feature/blackListedAddress

**Comment by vincss** [comment]
> btw. this returns a 404 https://github.com/vincss/mcsleepingserverstarter/tree/feature/blackListedAddress

Yes, I already merge it.
I will make a new release with the stuff for dynmap.
So you can use that binary : 
https://github.com/vincss/mcsleepingserverstarter/actions/runs/3997044837
Or the master branch.

**Comment by vincss** [comment]
The release is out : 
https://github.com/vincss/mcsleepingserverstarter/releases/tag/v1.3.0
