### ISSUE TITLE
Update to node-Minecraft-protocol 1.40.x for 1.19.3 support

### ISSUE THREAD

**Issue by DBraspberrypi** [vincss/mcsleepingserverstarter#134]
1.19.2 is now supported by node-Minecraft-protocol. Will this plugin be updated soon?

**Comment by vincss** [comment]
Hi !
There it is : 
https://github.com/vincss/mcsleepingserverstarter/releases/tag/v1.2.4
Have a nice day !

**Comment by DBraspberrypi** [comment]
Fantastic!!

**Comment by DBraspberrypi** [comment]
installing manually results in npm having 6 high vulnerabilities, is there something i have done wrong or have these not been patched yet?

**Comment by vincss** [comment]
Yes, it's due to some third party packages.

**Comment by Rysanlos** [comment]
1.40.0 is available for 1.19.3

**Comment by vincss** [comment]
Hi !
Thanks for the info, I will make a new release tommorow.

**Comment by vincss** [comment]
I tried to release a new version, something is wrong I created an issue : https://github.com/PrismarineJS/node-minecraft-protocol/issues/1073

**Comment by Rysanlos** [comment]
I updated to 1.40.0 yesterday (not 1.40.1) and it's working fine

**Comment by vincss** [comment]
Hi,
Maybe you can create a pull request with the working version, because I give it another try on with the version 1.40.0 and I still got the same error : 
        "minecraft-protocol": "1.40.0",

**Comment by Rysanlos** [comment]
All I did was changing
"minecraft-protocol": "^1.32.0",
to
"minecraft-protocol": "^1.40.0",
inside package.json
then npm install

I didn't reclone the repo or updated npm or edited any config files, the package.json version was 1.1.3
I'm not using the binaries

**Comment by sebasdt** [comment]
It seems like they fixed the issue and updated everything, according to https://github.com/PrismarineJS/node-minecraft-protocol/issues/1037#issuecomment-1399539253
so should be good to go, right?

**Comment by vincss** [comment]
Hi !
The new release is out :
https://github.com/vincss/mcsleepingserverstarter/releases/tag/v1.2.5
