### ISSUE TITLE
Minecraft Server inside docker completed

### ISSUE THREAD

**Issue by Jannik44** [vincss/mcsleepingserverstarter#135]
we talked already in #129  about docker and your code, i created a docker container out of it and uploaded it, you can integrate it in the readme or smth like that:
`docker run -d -p 65400:25565 -p 65401:19132/udp -v /home/minecraftserver:/home/mc --name jannik44-pnpmc --restart=always jannik44/pnpmc`
list of features i added:
https://hub.docker.com/r/jannik44/pnpmc

**Comment by vincss** [comment]
Hi,
Thanks for your contribution, you should be able to add a wiki page your self : 
![image](https://user-images.githubusercontent.com/2254806/212550276-704c3cb3-97f3-4d5e-801c-d624e3e7c0b3.png)

**Comment by Jannik44** [comment]
> Hi, Thanks for your contribution, you should be able to add a wiki page your self : ![image](https://user-images.githubusercontent.com/2254806/212550276-704c3cb3-97f3-4d5e-801c-d624e3e7c0b3.png)
cant see that button
![grafik](https://user-images.githubusercontent.com/76906033/212550403-1385d7b2-ed1f-4ec2-8ac2-71be376c77e3.png)

**Comment by vincss** [comment]
@Jannik44 , don't forget the wiki. ;-)

**Comment by Jannik44** [comment]
> @Jannik44 , don't forget the wiki. ;-)

ah right, forgot about it, thanks for reminding me, im currently very busy, i will do it as soon as i have the time for it ;) (end of the week maybe)

**Comment by vincss** [comment]
Bump and closing
