### ISSUE TITLE
Dynmap

### ISSUE THREAD

**Issue by Eros5646** [vincss/mcsleepingserverstarter#137]
Please specify how to get dynmap to work with sleepingserverstarter. It's too poorly explained for me and I'm having a hard time to fix it with my little knowledge to programming.  Also thanks for this awasome feature, its dropping my laptop from ~35w to ~4/6w when idle, running also with web server.

**Comment by vincss** [comment]
Yes, it was written before to have an internal web-server in SleepingServerStarter. I will check if something can be done to simplify the process.

**Comment by Jannik44** [comment]
dynmap works on my stuff, correct me when im wrong but i guess the webserver isnt stopping but the backend stuff so it displays a blank page or smth, maybe it should shut down completely somehow

**Comment by Eros5646** [comment]
It works fine now, I wrote it while being on like 1.2.3 version

**Comment by vincss** [comment]
I'm currently working on an integration for dynmap in the web-server, I will keep this open meanwhile.

**Comment by Rysanlos** [comment]
You can also access your Dynmap while the server is off if you can install Apache and do some configuration on your server machine. It's something about folder forwarding (but the chat won't work, I disabled it because I don't use it).
My Dynmap is available 24/24 even if the Minecraft server is off and without using the sleepingserverstarter implementation.

**Comment by vincss** [comment]
Yes I will try to make it work without the need of a Apache running, there is will some work to do.
https://github.com/vincss/mcsleepingserverstarter/wiki/Use-internal-SSS-WebServer-for-dynmap

**Comment by vincss** [comment]
Hi !
I made a branch with the functionality if you want to give it a try :
https://github.com/vincss/mcsleepingserverstarter/tree/feature/dynmap_webserver
Binaries : 
https://github.com/vincss/mcsleepingserverstarter/actions/runs/4046026403

**Comment by vincss** [comment]
The release with the dynmap feature is out :
https://github.com/vincss/mcsleepingserverstarter/releases/tag/v1.3.0
