### ISSUE TITLE
minecraft forge/sponge support

### ISSUE THREAD

**Issue by Jannik44** [vincss/mcsleepingserverstarter#138]
How about a version for modded forge/sponge servers? I mean they are really and i mean **really** power hungry, what do you think about that? is that a lot of work?

**Comment by vincss** [comment]
I already took a quick look a forge, it seems to work in a different way.

**Comment by Jannik44** [comment]
have a look at this script, its very old but back then they did it with bash, could an updated version of it do the job?

**Comment by GHYAKIMA** [comment]
mcEmptyServerStopper plugin port for Fabric 
[fabric-emptyserverstopper-mod](https://github.com/GHYAKIMA/fabric-emptyserverstopper-mod). 
It doesn't have config and requires **Fabric-API** to work. Tested on **1.19.2/3**

**Comment by Ibirtem** [comment]
Really looking forward to Forge support. It would be sooo wonderful!

**Comment by Jannik44** [comment]
> Really looking forward to Forge support. It would be sooo wonderful!

hey until a forge version is out you can use this bash script i wrote, it works with due to primitivity with all versions/ editions, sadly havent found a way to implement the minecraft protocol so it will show up as offline server but when you click join it does start the mc server etc.
it works for my forge mc server
(requires root to kill its sub processes)
[](https://cloud.mchost.fun/index.php/s/HLwDoyzMHzacixR)

**Comment by Ibirtem** [comment]
> (requires root to kill its sub processes)

so hate that most serv wrappers can't properly stop forge servers...
Dont think that i need script right know, but i can look in and test it!

**Comment by vincss** [comment]
I don't see why you tell that forge is not working, for me it's working just fine 
sleepingSettings.yml
`minecraftCommand: run.bat`

And in run.bat, remove the **pause** at the end and add nogui
`java @user_jvm_args.txt @libraries/net/minecraftforge/forge/1.19.3-44.1.0/win_args.txt **nogui** %*`

**Comment by Jannik44** [comment]
> I don't see why you tell that forge is not working, for me it's working just fine 
> sleepingSettings.yml
> `minecraftCommand: run.bat`
> 
> And in run.bat, remove the **pause** at the end and add nogui
> `java @user_jvm_args.txt @libraries/net/minecraftforge/forge/1.19.3-44.1.0/win_args.txt **nogui** %*`

i just did not test it because i am pretty sure its incompatible because of its differences but if you say the Minecraft protocol is the same for both thats great news👍

**Comment by GHYAKIMA** [comment]
> mcEmptyServerStopper plugin port for Fabric [fabric-emptyserverstopper-mod](https://github.com/GHYAKIMA/fabric-emptyserverstopper-mod). It doesn't have config and requires **Fabric-API** to work. Tested on **1.19.2/3**

Forge support has been added.

**Comment by vincss** [comment]
Hi !
It was in my todo list, thanks for the work. :-)
