### ISSUE TITLE
[pterodactyl] Server.jar and eula

### ISSUE THREAD

**Issue by WarrioR151** [vincss/mcsleepingserverstarter#139]
Hello, when user create server (pterodactyl) using pterodactyl egg for this, there is no installed server.jar in default, user need to manually install and put server.jar into server to start server, can you make it so the server.jar get installed with it on server start?
Thanks in advance

**Comment by vincss** [comment]
Hi !
It should download the .jar.
https://github.com/vincss/mcsleepingserverstarter/blob/master/docs/pufferpanel.json#L9
Maybe @BoredKevin  or @dada513  can have a look ?
I don't have a pterodactyl install that is ready to test, but I will try to get one.

**Comment by WarrioR151** [comment]
I'm on pterodactyl, not pufferpanel, also i found problem already
fixed

**Comment by vincss** [comment]
go into Install Script

and add

curl -o ${SERVER_JARFILE} ${DOWNLOAD_URL} under mv ${SERVER_JARFILE} ${SERVER_JARFILE}.old

like this:

if [ -f ${SERVER_JARFILE} ]; then
	mv ${SERVER_JARFILE} ${SERVER_JARFILE}.old
fi

curl -o ${SERVER_JARFILE} ${DOWNLOAD_URL}

if [ ! -f mcsleepingserverstarter-linux-x64 ]; then
    echo -e "Running curl -Lo mcsleepingserverstarter-linux-x64 https://github.com/vincss/mcsleepingserverstarter/releases/latest/download/mcsleepingserverstarter-linux-x64"
    curl -Lo mcsleepingserverstarter-linux-x64 https://github.com/vincss/mcsleepingserverstarter/releases/latest/download/mcsleepingserverstarter-linux-x64
fi
chmod +x mcsleepingserverstarter-linux-x64
Fixing issue https://github.com/vincss/mcsleepingserverstarter/issues/139

**Comment by vincss** [comment]
Hi !
I updated the file in the dynmap branch, can you try it ? 
https://github.com/vincss/mcsleepingserverstarter/blob/feature/dynmap_webserver/docs/egg-paper-mcsleepingserverstarter.json

**Comment by vincss** [comment]
I also noticed that the server-stopper is not included in the egg, shouldn't we add it ?

**Comment by WarrioR151** [comment]
My friend make docker image for me, so it will install server-stopper to server everytime their restart server, so i got this, i don't know how it will work when you add it directly into egg, so rather not add it, also some users don't like when they got installed plugins in their server without "knowing" it's better how it is, if someone need server-stopper, they can make docker image, keep it like it is now

**Comment by vincss** [comment]
It should be fixed in the master branch now (add server-stopper added).

**Comment by vincss** [comment]
No news.
