### ISSUE TITLE
quit command

### ISSUE THREAD

**Issue by WarrioR151** [vincss/mcsleepingserverstarter#142]
Hey, hi can i remove somehow the "quit" command to start server? I'm on pterodactyl, users just can bypass this by setting cron job to write quit, or by plugin they can just send command quit, can i remove it so that command will not work?

**Comment by vincss** [comment]
Hi,
It's weird that users can set cron and send command, it should be only for admin.
I can put a setting for that if needed.

**Comment by WarrioR151** [comment]
Nonoo, i mean, i have free server hosting
when user make server, he is owner logically, i just need to completely remove the "quit" command or text or whatever is it so when they write quit in console, it just do nothing, can i somehow remove that command from function?

**Comment by vincss** [comment]
Hi !
I added the parameter preventStop in the current branche :
https://github.com/vincss/mcsleepingserverstarter/tree/feature/dynmap_webserver
Binary
https://github.com/vincss/mcsleepingserverstarter/actions/runs/4052252458

**Comment by WarrioR151** [comment]
How can i set that preventStop? https://imgur.com/CmkLMih

i added binary, but quit still works, how can i preventStop toggle?

**Comment by WarrioR151** [comment]
Hey, hello it works great! Thank you, but you added something new, in console it shows 

"A Prince has taken a quick peek. [1.19.3_::ffff:91.***.**.**] "

can you revert it back like before so it not show IP? It's not very good when it Show IP of users who refresh server-list, not good for their privacy

**Comment by vincss** [comment]
Hi,
The logs should be accessible only from an admin, and it could be helpful to have it.
Can you explain me how your setup is working ?

**Comment by vincss** [comment]
The released version is out : 
https://github.com/vincss/mcsleepingserverstarter/releases/tag/v1.3.0
