### ISSUE TITLE
Problem with launching on linuxgsm

### ISSUE THREAD

**Issue by dam2452** [vincss/mcsleepingserverstarter#143]
When I try to run your script through linuxgsm it doesn't work :
![image](https://user-images.githubusercontent.com/81230036/216337199-88844c16-2d1c-47d4-9f9e-7e433a555862.png)
/

**Comment by vincss** [comment]
Hi,
As it written, It doesn't find your spigot.jar
How do you install it with linuxgsm ?

**Comment by dam2452** [comment]
I use this tutorial to replace executable file 
https://www.reddit.com/r/Minecraft/comments/thjrhf/lgsm_minecraft_server_forge_howto/
![image](https://user-images.githubusercontent.com/81230036/216347214-7f1ea30c-121e-44d1-b2ec-3f25772630e5.png)

**Comment by vincss** [comment]
- You should download the lastest version from paper mc : https://papermc.io/downloads
- Rename it to spigot.jar, and put it next to the sleepingServerStarter.run

**Comment by dam2452** [comment]
I'm using Magma, which is a combination of Paper and Forge. You should also know that when I run the executable manually from the LGSM, it works. So the problem probably lies somewhere else.

**Comment by dam2452** [comment]
When I use the command "/home/mcserver/serverfiles/sleepingServerStarter.run" or "./sleepingServerStarter.run" to run your script, everything works perfectly. But when your script tries to run through LinuxGSM, there is a problem.

**Comment by vincss** [comment]
Maybe you should set the parameters
minecraftWorkingDirectory
https://github.com/vincss/mcsleepingserverstarter#%EF%B8%8F-settings

**Comment by dam2452** [comment]
![image](https://user-images.githubusercontent.com/81230036/216390622-b6b90e4c-d385-433a-89a4-10f1f1c9969c.png)
![image](https://user-images.githubusercontent.com/81230036/216390703-59788b64-38e8-4ea8-b88a-9e807bb8d03a.png)
 Still the same

**Comment by dam2452** [comment]
"And I can't enter any command while it's supposedly working and normally it switches to the console separately on linuxgsm.

**Comment by vincss** [comment]
It seems that you are editing the wrong file.
Look at the setting that are loaded : 
![image](https://user-images.githubusercontent.com/2254806/216391854-5238b1d9-31df-41ab-9e98-b4b3e2267426.png)

**Comment by dam2452** [comment]
Do you mean that I entered the additional parameter 'minecraftWorkingDirectory' in the wrong place, or is there something wrong with linuxGSM? Because the path in linuxGSM seems to be correct, as the ghost server that launches the actual server is working, even though it doesn't turn on the actual server when trying to enter, but the ghost server is standing, so your script is being executed.

**Comment by vincss** [comment]
> I use this tutorial to replace executable file https://www.reddit.com/r/Minecraft/comments/thjrhf/lgsm_minecraft_server_forge_howto/ ![image](https://user-images.githubusercontent.com/81230036/216347214-7f1ea30c-121e-44d1-b2ec-3f25772630e5.png)

As you say here, the executable is located by it's absolute path.
Can't you set the working directory in LGSM and launch only with ./sleepingServerStarter.run ?             
Or the sleepingSetting.yml that is used is located next to your LGSM executable, and you have to edit this one.

**Comment by dam2452** [comment]
![image](https://user-images.githubusercontent.com/81230036/216430642-c2def7ac-f631-42bc-934a-5417d34fe8ff.png)

**Comment by vincss** [comment]
Maybe try adding the following to your mcserver.cfg :
executabledir="/home/mcserver/serverfiles/"
executable="./sleepingServerStarter.run"

https://github.com/GameServerManagers/LinuxGSM/blob/master/lgsm/config-default/config-lgsm/rustserver/_default.cfg#L177
