### ISSUE TITLE
[Feature Request] Disable force-key-authentication

### ISSUE THREAD

**Issue by LuckCrafter** [vincss/mcsleepingserverstarter#144]
With some mods the new public key security standard does not work.
A workaround is, to disable the online mode, but yea, now cracked players could also start the server ._.
I would like a setting, for disabling the force-key-authentication like velocity does this.

**Comment by vincss** [comment]
Hi,
I don't have a way to test it, I would have to make a special version for you to test it.
Did you run the binary or the source ?
If you run from the source, you can try to change this parameter : 
https://github.com/vincss/mcsleepingserverstarter/blob/master/src/sleepingMcJava.ts#L36

**Comment by LuckCrafter** [comment]
I run the binary, but I could also build it from source. I will look at it later

**Comment by vincss** [comment]
Any news ?
