### ISSUE TITLE
[Feature Request] Add Whitelist

### ISSUE THREAD

**Issue by LuckCrafter** [vincss/mcsleepingserverstarter#145]
It would be nice if only players who are on the whitelist start the server when it is stopped. So if the whitelist is activated of course.

**Comment by vincss** [comment]
Hi,
Did you changed the default port ?
There should be less people connecting to it.

**Comment by JustGuardian** [comment]
It would be very useful. Since I am using ngrok to host my server, sometimes some random people starts my server and I don't want this lol

**Comment by vincss** [comment]
Hi !
A new version is out with the whiteListedNames added.
