### ISSUE TITLE
webui error

### ISSUE THREAD

**Issue by Jannik44** [vincss/mcsleepingserverstarter#148]
hello, i get this error on the webui, am i missing some dependencies? installed apache2

![image](https://user-images.githubusercontent.com/76906033/216766806-f31c80fb-86d0-452d-862d-b2d8eea39ee0.png)

**Comment by vincss** [comment]
Hi !
Thanks for the quick feedback indeed there was an error in the packaging.
I made a new executable which should be ok : https://github.com/vincss/mcsleepingserverstarter/releases/tag/v1.3.0
