### ISSUE TITLE
Having an issue with it not restarting after server is stopped 

### ISSUE THREAD

**Issue by Iampaddyman** [vincss/mcsleepingserverstarter#150]
Seems like after the server is stopped by any way it is not beginning the "sleepingserverstarter" protocol and thus becoming inactive till i close the current batch and manually rerun the batch.
this is a new problem that appeared seemingly at random, I'm speculating that it has something to do with the server not stopping correctly and thus not actually rerunning "sleepingserverstarter".
Please correct me on this cause im very new to running servers.
[sleepingServer.log](https://github.com/vincss/mcsleepingserverstarter/files/10903971/sleepingServer.log)
[latest.log](https://github.com/vincss/mcsleepingserverstarter/files/10903972/latest.log)
if you need more information I can try to provide you with it.

**Comment by vincss** [comment]
Are you still having the issue ?
I made a new version with the latest protocol included. Maybe there is an internal fix for your issue.
