### ISSUE TITLE
[Question] Is there a way to use the blacklist as an allowlist?

### ISSUE THREAD

**Issue by TheJazzGamer** [vincss/mcsleepingserverstarter#152]
Hey, I really like this idea, but I think sometimes just random people will start up you server. You obviously don't want this. I saw there was already a request for a whitelist, but I thought maybe you could just say in the blacklist 'everybody exept those IP adresses'. Would this be possible and if it is, how would it be done?

**Comment by vincss** [comment]
Hi,
For now, it's not possible.
I will close this thread, feel free to follow on : https://github.com/vincss/mcsleepingserverstarter/issues/152

**Comment by vincss** [comment]
Hi !
A new version is out with the whiteListedNames added.
