### ISSUE TITLE
./mcsleepingserverstarter-linux-x64: 2: Syntax error: Unterminated quoted string

### ISSUE THREAD

**Issue by Hexatronic01** [vincss/mcsleepingserverstarter#158]
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: Checking server disk space usage, this could take a few seconds...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from pterodactyl/yolks 
Digest: sha256:3a5668af21eddb2d27aabf31b6bee0a8b5a4cd39b620a9a4c7550397a8c17b0d 
Status: Image is up to date for ghcr.io/pterodactyl/yolks:java_17 
[Pterodactyl Daemon]: Finished pulling Docker container image
container@pterodactyl~ java -version
openjdk version "17.0.6" 2023-01-17
OpenJDK Runtime Environment Temurin-17.0.6+10 (build 17.0.6+10)
OpenJDK 64-Bit Server VM Temurin-17.0.6+10 (build 17.0.6+10, mixed mode, sharing)
container@pterodactyl~ ./mcsleepingserverstarter-linux-x64
./mcsleepingserverstarter-linux-x64: 2: Syntax error: Unterminated quoted string
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 2
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago.

**Comment by vincss** [comment]
Hi,

I cannot reproduce that one.

Can you : 
- Be nice and say Hi.
- Describe your setup and how to reproduce your issue (which versions are you using, which steps did you perform).
- Try to reproduce with the latest version of the config : https://github.com/vincss/mcsleepingserverstarter/blob/master/docs/egg-paper-mcsleepingserverstarter.json

Thanks :-)
