### ISSUE TITLE
Error: Chunk size is 1418 but only 3 was read

### ISSUE THREAD

**Issue by Qesaru** [vincss/mcsleepingserverstarter#164]
I got Sleeping Server Starter running. Up until yesterday I had everything working, I didn't change anything since then.
I got the same problem once a couple of days ago, but I could resolve it by just starting the Minecraft Server itself once. This doesn't help anymore. 
I run the program inside a Docker Container in Pterodactyl, but I don't use your Egg because I made this configuration before you made the Egg. 
I already tried the newest and second to newest version of the program, but they give me the same error.
Now here's the problem:

When I try to connect to my Minecraft server, it won't tell me that the server is about to wake up, instead it just tries to connect until it's "unable to connect to server".
The cli output tells me about the Prince, but as soon as I try to connect, it gives this Error:
`Chunk size is 1418 but only 3 was read ; partial packet : {"name":"legacy_server_list_ping","params":{"payload":10}}; buffer :fe010a00f605f60a6d632e7165736172752e64650038372e3132322e3130332e313035003166383238336138653339333465323661323030643435363264323233636337005b7b226e616d65223a227465787475726573222c2276616c7565223a2265776f6749434a306157316c633352686258416949446f674d5459344d4455324e7a45784e6a417a4e43774b4943416963484a765a6d6c735a556c6b49694136494349785a6a67794f444e684f47557a4f544d305a544932595449774d4751304e5459795a4449794d324e6a4e79497343694167496e427962325a706247564f5957316c4969413649434a525a584e68636e55694c416f6749434a7a6157647559585231636d56535a58463161584a6c5a4349674f694230636e566c4c416f6749434a305a58683064584a6c637949674f69423743694167494341695530744a546949674f694237436941674943416749434a31636d776949446f67496d6830644841364c7939305a58683064584a6c637935746157356c59334a685a6e5175626d56304c33526c65485231636d55765a57557a596a45334e7a526c5a5455304d54677a4d44413259324e6a4e325131597a59784f4449324d7a677a4d546c685a57466d5a4759314d7a566d4e324e694d5745304e445a6b595455344e54557a59546c6d4d43494b4943416749483073436941674943416951304651525349674f694237436941674943416749434a31636d776949446f67496d6830644841364c7939305a58683064584a6c637935746157356c59334a685a6e5175626d56304c33526c65485231636d55764d6a4d304d474d775a54417a5a4751794e4745784d5749784e574534596a4d7a597a4a684e3255355a544d7959574a694d6a41314d5749794e4467785a4442695954646b5a575a6b4e6a4d315932453359546b7a4d79494b494341674948304b49434239436e305c7530303364222c227369676e6174757265223a2273554352696f65777137574f4f36385656414a5a384e416b446c6a4f3746334c485637327557626b386c7556613337772b69324e5771774877554c31344c307076494d5776473764324d5638385474724835397167596f4e775175446e6e2b4e2b6c624670464b32574a58375776466d2b4e3373637654453277466331766f6731576a794974464d35674b57316754706b617949474b5039756a51616a3579646c644551484e487462785a636a5276433044453658587149726e723032724f3764666744646838497076353155724e766b66412b494f7331786c537a3855334258354146454a4f514d33684349542f696a6a31686b6f4c724c74637866735a46536a3256356868676b5a5a76664447534c724f694864646d33566a563342454c6638644c4f684c45414b754373692b4b3953726c4b384f71502f775864655678544274674b73362f573843684c46697636397959722f41645250792f456f667770314234326863426951454e496466335379376a7030655739314f4855736a616839386b687168424c4a67515473466f426d376e535753654b574d71444936715a51644877746c544f4b776c5849324f6d4b734877753663734e6a3733594e49593847415a713167656c6938395441534d386848395032324f393153374b494e572f716e4d7155524749454169422b796e4336314b2f49556443736f6e79773168747735364c37774b652f4a46666e67555a6a5134565448456441516734346d6550617a4e536841474c32734e456147434b67503753625337774e6979704e2b39313132364b58437673706f704c566244786241736d454c394e5978342b36436b697133444874454e347963634a4d5a64695573416f656f36477871755464574b494e3071513076554154797279445363496e7175696a6571752b70597156366a7633717341636e2b4b735c7530303364227d5d63dd02080006516573617275`

**Comment by vincss** [comment]
Hi,
can you tell me which version are you using, mcsleeping and minecraft?

**Comment by Qesaru** [comment]
> Hi, can you tell me which version are you using, mcsleeping and minecraft?

Hey,
I tried mcsleeping v1.5.3, v1.5.2 and an older version that I've downloaded a couple of months ago. All of them share the same Issue.
I forgot to mention, I'm running a Paper server. It's using Minecraft v1.18.2 and Paper version git-Paper-287

**Comment by vincss** [comment]
Maybe try with the latest 1.5.x

**Comment by Qesaru** [comment]
> Maybe try with the latest 1.5.x

I thought, I'd already tried the newest version.
Turns out I was wrong. The newest version works just fine.
Thank you very much for your help and for this awesome product.
