### ISSUE TITLE
Feature Request: log ip adresses and software version

### ISSUE THREAD

**Issue by Jannik44** [vincss/mcsleepingserverstarter#167]
Hello, in version 1.3.0 you introduced the blacklisted adresses, and thats nice, but i have to dig through the entire network traffic to find the bot ip wich started the server, can you please add the ip adresses from everyonw who pinged and also who sent the join request? This would be very helpful :)
![prince](https://user-images.githubusercontent.com/76906033/232250561-e0ed8b66-e6ae-4ec0-8cb7-71043f437d23.png)

Also there are multiple software versions and i dont know if its outdated or not, can you also log at every server start/stop what version is installed and if its outdated?

Thanks in advance, i apprechiate your work :100: have a great day :)

**Comment by vincss** [comment]
It should be included in the lastest version : 
https://github.com/vincss/mcsleepingserverstarter/blob/master/src/sleepingMcJava.ts#L44

I will add the version number in start/stop log.

**Comment by vincss** [comment]
The new version with more logs is out : 
https://github.com/vincss/mcsleepingserverstarter/releases/tag/v1.5.4

**Comment by vincss** [comment]
Hi,
Done ;-)
https://github.com/vincss/mcsleepingserverstarter/releases/tag/v1.5.5

**Comment by Jannik44** [comment]
hey, looks like it does only log playernames not ip adresses
https://i.imgur.com/FDqz5su.png

**Comment by vincss** [comment]
Hi,
Which settings are you using ?
It works fine on my side.

**Comment by Jannik44** [comment]
looks like the problem is gone i rebuilt the docker container and it works now, thanks
![grafik](https://user-images.githubusercontent.com/76906033/234097313-ba654874-1bfd-4ed5-a7a5-7583a22bad4a.png)
