### ISSUE TITLE
Feature Request: default blacklisted ips

### ISSUE THREAD

**Issue by Jannik44** [vincss/mcsleepingserverstarter#170]
Hello, as you know there are programs out there wich go through the ipv4 range and join servers, my minecraftserver is now up for a few months and there are lots of them but these dont cause any issues, the problem were the bots wich join and i think the known ones should be blocked by default as this makes server administration easier, also there are bots with malicious intentions, looks like they send lots of traffic etc. Here my suggestion of ips that should be blocked from starting the server by default, i will add more when i see more, i think its good to add the list by default

https://mcmaps.neocities.org/dangerous_ips.txt

**Comment by vincss** [comment]
You can make a pull request to add it in the default configuration file :
https://github.com/vincss/mcsleepingserverstarter/commit/350a948fe0cf3b4ff5c139d5329f01532dbbbe9f
