### ISSUE TITLE
Suggestion: Allow any command in the "minecraftCommand" in sleepingSettings.yml

### ISSUE THREAD

**Issue by PlayerEngineer** [vincss/mcsleepingserverstarter#175]
Currently, when I put a command to a batch file in minecraftCommand it throws an error. It would be very nice for custom setups.

**Comment by vincss** [comment]
Hi!
It should work with a batch, can you give an example of batch and settings that doesn't work?

**Comment by PlayerEngineer** [comment]
I sincerely apologize I did not put quotes in my original command. It works now
