### ISSUE TITLE
Error with rootless docker containers due to logs folder.

### ISSUE THREAD

**Issue by kitsumed** [vincss/mcsleepingserverstarter#184]
When setting up a server on a docker container, I had to make sure that the process was running with rootless permissions so that the minecraft server couldn't be a root user. By doing so, I realized that your image required another volume/bind argument (FULL_PATH/logs:/logs) that wasn't mentioned on the wiki. While the error throw by the logs folder missing wasn't preventing the program to work, not having the bind was making it impossible to attach to the console due to the error.

Please also see https://github.com/vincss/mcsleepingserverstarter/issues/185

**Comment by vincss** [comment]
Hi !
Thanks for the submission.
@markmetcalfe , can you help ?

**Comment by markmetcalfe** [comment]
@vincss I am traveling for the next few weeks so will not be able to help. Thanks @kitsumed for raising this issue - we should update the Dockerfile so that the server is not run as root like you say.

**Comment by kitsumed** [comment]
> @vincss I am traveling for the next few weeks so will not be able to help. Thanks @kitsumed for raising this issue - we should update the Dockerfile so that the server is not run as root like you say.

Had to write a reply fast so I just translated from my main language insead of writing it in english. I may edit this message later.

FR: En attendant, même si l'image du docker run en root, vous avez toujour la possibilité de run le process avec un user rootless en mentionnant un user avant le démarrage du docker. Je me rapelle aussi avoir désactiver toutes les capacités par défaut du container.

EN : In the meantime, even if the docker run image has root, you can still run the process with a rootless user by specifying a user before starting the docker. I also remember disabling all the container's default capabilities.

**Comment by kitsumed** [comment]
Any updates? @vincss @markmetcalfe

**Comment by markmetcalfe** [comment]
Have got a fix for this in #198
