### ISSUE TITLE
Add a settings to disable the save of logs for docker containers

### ISSUE THREAD

**Issue by kitsumed** [vincss/mcsleepingserverstarter#185]
Hey, I was wondering if you could add a setting to disable the save of logs. Since the docker containers already save the logs of the console, saving another .log file is useless in this case and will end up taking space for nothing.

**Comment by vincss** [comment]
Hi, 
yes it can be done. :-)

**Comment by vincss** [comment]
I've made a new version : 
https://github.com/vincss/mcsleepingserverstarter/pkgs/container/mcsleepingserverstarter 
You can add an environment variable to disable the file logs, in docker-compose add : 
    environment:
      - TZ=Europe/Brussels # Change to your timezone so that the log timestamps are correct
      **- DISABLE_FILE_LOGS=true**

**Comment by kitsumed** [comment]
You forgot to change the version display under package.json. I don't think it's a major issue so not pushing a fix right now should be fine, I guess.

That aside, the new update is working fine 👍
