### ISSUE TITLE
Being flagged as a trojan

### ISSUE THREAD

**Issue by iwanmilk** [vincss/mcsleepingserverstarter#187]
i ran the file through virus total and hybrid analysis and its getting flagged as a trojan. is it true or false

**Comment by vincss** [comment]
I don't know why it would be flagged as a trojan. 

![image](https://github.com/vincss/mcsleepingserverstarter/assets/2254806/02eafd81-b952-4c35-88f4-8dec31bbd73a)

**Comment by iwanmilk** [comment]
this is what its saying for me
![image](https://github.com/vincss/mcsleepingserverstarter/assets/128271102/c0ed2f2a-f1d3-48aa-9d6a-9d7346dd5cbc)

**Comment by iwanmilk** [comment]
i did more research on the vendor and people keep saying it flags them as false positives. if its fine on your end i trust it.

**Comment by vincss** [comment]
As the software rely on third party pieces, there is always a risk like in every software.
