### ISSUE TITLE
[Suggestion] Option to hide `quick peek` logs

### ISSUE THREAD

**Issue by qaziok** [vincss/mcsleepingserverstarter#188]
Hey, I have been using your docker image for some time now, but now I created check for safety stop the machine that's running my server, and it really spams my logs with `info: A Prince has taken a quick peek`. Any plans to add ENV to hide those logs?

**Comment by vincss** [comment]
Hi, 
Not for now, it's a specific use case , but I could if there is similar needs.

**Comment by nisheri-ascar** [comment]
Same here, with using Geyser it can be annoying logs spamming with it

**Comment by vincss** [comment]
Hi,
I added the setting you can give it a https://github.com/vincss/mcsleepingserverstarter/releases/tag/v1.6.0
