### ISSUE TITLE
Bedrock shows large amount of online players and refuses connection

### ISSUE THREAD

**Issue by Just-Leah** [vincss/mcsleepingserverstarter#19]
When I have the server sleeping, if someone tries to connect via bedrock edition through LAN, the amount of online players shows an extremely large number that clips into the green circle next to it, and when you try to connect, the client says “This server is too popular, wait a bit for it to free up some space”. This renders starting the server via LAN bedrock impossible. I am unable to get some example screenshots for more info right now, but I will try and get some as soon as possible.

**Comment by Stonewall0210** [comment]
Added some screenshots of the bug, censored the IP address of the server

**The server in the LAN games list**
![98D2A005-D368-4C86-84D6-9E31E329B4D4](https://user-images.githubusercontent.com/76092465/111005950-940cb480-83d7-11eb-98e9-ab6f4181f18c.jpeg)

**The message on attempt to connect**
![B94838D9-3829-4745-8B6C-37DA98BD2C2E](https://user-images.githubusercontent.com/76092465/111005953-9707a500-83d7-11eb-8cfb-83c7b84d9833.jpeg)

**Comment by vincss** [comment]
That's strange, I cannot reproduce on my setup.
Which versions on what platform are you using ?

**Comment by d1ddle** [comment]
I get the same message when joining from Xbox. Just tried it. 
Bedrock PC is fine
Bedrock v1.16.210
Geyser Compatible

**Comment by Stonewall0210** [comment]
I’m on version 1.16.210 as well, on an IPad.
The normal problem occurs on my brother’s iPad but on mine the same number shows except it’s negative.
I’m pretty sure that he’s on the same update because there was a point where geyser wouldn’t let him connect and I had to update it.

**Comment by d1ddle** [comment]
Could be something to do with the Protocols being changed and info being read from packets where it shouldn't. Of course I could be completely wrong, but [this](https://minecraft.gamepedia.com/Protocol_version#Bedrock_Edition_2) gives me a good idea..

**Comment by vincss** [comment]
Hi ! Maybe you could join our discord support private chat and try to debug it together, unfortunatly, I don't have a Xbox One to try it.
https://discord.gg/5DrncMSC (available 24h)

**Comment by ArmoredFuzzball** [comment]
I am having the same issue on the mobile Bedrock Edition. When the server is asleep there is a huge amount of players online, preventing joining (also, setting the max player count to -1 does not work). I am on the most recent version of Bedrock (v1.16.220) and the most recent version of the sleep system.
I'm using a plugin called Geyser for Bedrock players to connect to the Java server. At first I thought that was the issue, but after seeing this, it may not be Geyser's fault. 
I noticed that when I first manually start the server the player count begins as a very large negative number of players over 0 (eg. -5732562/0), which DOES allow you to join, but after the server shuts down and restarts with the suggested sleep plugin, the number is just very big, and you can no longer join! 
I hope this info helps.
Also, sorry if I should have opened my own issue, first time poster here.
Thanks!

**Comment by Stonewall0210** [comment]
Most plugins would not matter as the issue here is present while the server is offline, if that makes sense

**Comment by vincss** [comment]
I added a web-gui so mobile player can launch the server since bedrock support is still WIP by the library.

**Comment by vincss** [comment]
There is a new version to support bedrock: 

https://github.com/vincss/mcsleepingserverstarter/releases

https://github.com/vincss/mcsleepingserverstarter/issues/130#issuecomment-2456593608
