### ISSUE TITLE
Pretty high RAM usage: 100mb

### ISSUE THREAD

**Issue by f1refa11** [vincss/mcsleepingserverstarter#192]
ik for some people 100mb usage is ok, but I think that memory usage for a simple port listening app is really high.

os: Linux Debian 12 amd64
version: 1.5.12
web server: disabled
binary file: from github releases

**Comment by vincss** [comment]
Hi,
Yes I know the ram usage is pretty high for a simple software, it's due to the fact that it rely on node ( & pkg when using binary ) and it's not a native software.
I've already look at some improvement but didn't find much. If you have suggestions. :-)

**Comment by obj-obj** [comment]
@f1refa11 if you really need lower ram usage, you could check out [lazymc](https://github.com/timvisee/lazymc). According to the README, it uses 3 KB of RAM.
