### ISSUE TITLE
Did JSPrismarine update to 1.20?

### ISSUE THREAD

**Issue by SkyKingPX** [vincss/mcsleepingserverstarter#195]

**Comment by vincss** [comment]
There is already an issue opened for that, in which you already commented : 
https://github.com/vincss/mcsleepingserverstarter/issues/130

They made an update which is not compatible with classic node js project : 
https://github.com/JSPrismarine/JSPrismarine/issues/1016
PS: Don't forget to be nice, say Hi, and give some contexts next time.

**Comment by SkyKingPX** [comment]
Oh sorry

**Comment by vincss** [comment]
I will update the related tickets ^^
