### ISSUE TITLE
some modules appear to be missing 

### ISSUE THREAD

**Issue by Manazzez** [vincss/mcsleepingserverstarter#196]
I was trying to set this up on 1.20.1 server and everything went fine until i had to start the server 
I ran the last command "-npm start" and it gave me a few errors related to missing modules and some other stuff
![Screenshot (1)](https://github.com/vincss/mcsleepingserverstarter/assets/142537334/b816fcbd-ebc1-403c-a2a3-c5d4dc974755)

**Comment by vincss** [comment]
Hi,
I think you updated the jsprimarine packages, did you try to run npm ci before running npm start ?

**Comment by Manazzez** [comment]
Sup man, 
I tried to run said command before starting the server and It still gave me those errors
but now I tried to use the .exe and it worked out flawlessly. Thanks for help anyways man 🫂

**Comment by Craters12** [comment]
what is the .exe? all i can think of the the cmd.exe.

**Comment by Manazzez** [comment]
Sorry for not making it clear enough
I saw there also was a "mcsleepingserverstarter-win-x64.exe" that i could download, just simply put on the server folder and run it just like the start.bat file.
but It also has a few issues, whenever I load the server and type something in chat i get kicked out. The console says that:

Manazzez lost connection: Received chat packet with missing or invalid signature.

and the first time I tried to say anything in chat the game gave me a message saying that I couldn't send anything in the chat because the chat messaging system had been disabled

**Comment by Manazzez** [comment]
found the solution to getting kicked out of the server 🤦
I just had to set enforce-secure-profile to false

**Comment by Craters12** [comment]
It works now. Thanks a lot! Dose the sleeping settings still work on it or is it just its own thing now?

**Comment by Manazzez** [comment]
yup, just copy all the stuff from the .rar file into the server folder and use the .exe instead
