### ISSUE TITLE
[ Question / Feature Request ] Scheduled uptime

### ISSUE THREAD

**Issue by xEmp3ror** [vincss/mcsleepingserverstarter#199]
Is there a way to allow players to wake up the server only during a specific time slot? For example: "weekdays from 8pm to 2am and 24h weekends". Something like that.

**Comment by vincss** [comment]
Hi,
it's not possible in the software as it is.
But you can rely on mecanism from your OS like cron or schedule https://docs.active-directory-wp.com/Usage/How_to_add_a_cron_job_on_Windows/Scheduled_tasks_and_cron_jobs_on_Windows/index.html

**Comment by vincss** [comment]
> Is there a way to allow players to wake up the server only during a specific time slot? For example: "weekdays from 8pm to 2am and 24h weekends". Something like that.

Did you manage to put in place what you wanted ?
If yes, can you write a small how to in the wiki ?
