### ISSUE TITLE
Add memory options and web maps.

### ISSUE THREAD

**Issue by Shapaper** [vincss/mcsleepingserverstarter#201]
1.Can we add a configuration option? Only start MC when memory is above a certain amount?
2.Can it support a web map called Bluemap? 
Translated by new Bing!

**Comment by vincss** [comment]
Hi !
1. Could be done, but I don't think I will do it.
2. You can set the webServeDynmap path to whatever you want, I don't know how Bluemap is working.

**Comment by Shapaper** [comment]
It may not be very polite for me to ask questions again😂, but I still want to ask why the memory detection function is not added to prevent the memory from exceeding the standard. From my understanding, it shouldn’t be too troublesome🤔. In addition, bluemap is very similar to dynmap, but it may have several resource files that cannot be accessed in a static way. For example, a timestamp of the get request will be added after the block data URL. You can actually access it by ignoring the timestamp. (Why Why don’t you try the 3D web map, as long as it already supports 2D😢)

**Comment by vincss** [comment]
It's open-source, feel free to do a Pull Request. ;-)

**Comment by Shapaper** [comment]
Okay, thank you for your answer, I'll try my best
