### ISSUE TITLE
Error on prebuild rimraf on npm start

### ISSUE THREAD

**Issue by kittenvr** [vincss/mcsleepingserverstarter#206]
![20231018_165026.jpg](https://github.com/vincss/mcsleepingserverstarter/assets/103120356/2ccedf70-d860-4c8b-b97d-5cbfcbf0c90f)

**Comment by vincss** [comment]
Did you do a "npm ci" before your "npm start" ?

**Comment by lightningnull** [comment]
I have a problem like this and I did what you said, but my problem was not solved

**Comment by vincss** [comment]
Did you try using the binary instead ? It should be easier if you don't have much experience in programming.

**Comment by lightningnull** [comment]
My problem was solved. The problem was that the Linux package manager installed the wrong version of NodeJS

**Comment by vincss** [comment]
> My problem was solved. The problem was that the Linux package manager installed the wrong version of NodeJS

Thanks for the update !

**Comment by vincss** [comment]
> ![20231018_165026.jpg](https://user-images.githubusercontent.com/103120356/276298716-2ccedf70-d860-4c8b-b97d-5cbfcbf0c90f.jpg)

Any news ? 
Did you try with the binaries ? 
https://github.com/vincss/mcsleepingserverstarter/blob/master/README.md#-download-the-binaries-easiest

**Comment by kittenvr** [comment]
> > ![20231018_165026.jpg](https://user-images.githubusercontent.com/103120356/276298716-2ccedf70-d860-4c8b-b97d-5cbfcbf0c90f.jpg)
> 
> Any news ? Did you try with the binaries ? https://github.com/vincss/mcsleepingserverstarter/blob/master/README.md#-download-the-binaries-easiest

no, havent tried partly because i dont think it works for 1.20.2
