### ISSUE TITLE
These errors show up every time I want to open the server(or start mcsleepingserver process), is this a problem from this plugin? Or maybe another plugin?

### ISSUE THREAD

**Issue by VikingLord501st** [vincss/mcsleepingserverstarter#209]
![Screenshot (1043)](https://github.com/vincss/mcsleepingserverstarter/assets/111013084/cb67d5ad-7f3c-4d6d-a3b5-9ea060097fef)

**Comment by Salamando1** [comment]
just use the mcsleepingserverstarter-win-x64.exe file for it

**Comment by NoobisJ** [comment]
https://github.com/vincss/mcsleepingserverstarter/releases?page=4

**Comment by VikingLord501st** [comment]
> https://github.com/vincss/mcsleepingserverstarter/releases?page=4

What do I do with these files, like where do I place them?

**Comment by VikingLord501st** [comment]
> https://github.com/vincss/mcsleepingserverstarter/releases?page=4

I get this message now
![Screenshot (1044)](https://github.com/vincss/mcsleepingserverstarter/assets/111013084/fc747931-2907-4216-8ac3-92995cade2e9)

**Comment by VikingLord501st** [comment]
![image](https://github.com/vincss/mcsleepingserverstarter/assets/111013084/ec1e4dc1-6678-4edf-92b8-9e6e037ed1d8)

**Comment by VikingLord501st** [comment]
![Screenshot (1045)](https://github.com/vincss/mcsleepingserverstarter/assets/111013084/dba32870-1011-4889-a099-159a43ab60b3)

**Comment by VikingLord501st** [comment]
> https://github.com/vincss/mcsleepingserverstarter/releases?page=4

Ignore the other two images. My server runs on a private desktop, on that desktop, I've managed to log on to the server with a minecraft instance. On my private laptop I am unable too. I've had this issue before, do you know how to fix it? I know its not too complicated but can't find how online.

**Comment by NoobisJ** [comment]
https://m.youtube.com/watch?v=WqvQISpr6-s


Watch and follow steps but also put the exe into the server folder

**Comment by vincss** [comment]
> https://github.com/vincss/mcsleepingserverstarter/releases?page=4

You mentioned an older version, use the latest : https://github.com/vincss/mcsleepingserverstarter/releases/tag/v1.7.1

**Comment by NoobisJ** [comment]
Oh sorry for giving u an older ver u should like for what file fits ur server

**Comment by VikingLord501st** [comment]
Updating the version helped.

**Comment by NoobisJ** [comment]
Show me what's the problem ur updating what?

**Comment by NoobisJ** [comment]
> ![Screenshot (1045)](https://github.com/vincss/mcsleepingserverstarter/assets/111013084/dba32870-1011-4889-a099-159a43ab60b3)
> 
> 

This means that u have 2 applications open
Close one or all of them if that doesn't work best option is restart ur computer and open it up again

**Comment by NoobisJ** [comment]
Updating Minecraft ver?
