### ISSUE TITLE
Server doesn't start after pinging it 1.16.4

### ISSUE THREAD

**Issue by Sanaan01** [vincss/mcsleepingserverstarter#21]
I have two versions of Java on my PC. I used a server start up bat like this.
![image](https://user-images.githubusercontent.com/81903566/113504269-ac3ba380-953f-11eb-8fe7-6d81f89edcb1.png)

When i input the same line of code here 
![image](https://user-images.githubusercontent.com/81903566/113504280-bf4e7380-953f-11eb-81dd-5b5aef309a71.png)
It doesn't work and the npm window crashes

**Comment by Sanaan01** [comment]
![image](https://user-images.githubusercontent.com/81903566/113507297-3b51b700-9552-11eb-90c6-37bb0aed3ba2.png)
I get this error

**Comment by vincss** [comment]
Hi !
Maybe you can try be pointing directly on the .bat.
Or put the full path to your jar, I think that your working directly doesn't contain your paper.jar.

Or either use a variable that contain the current path like, don't forget to use " " when there is space in your path :
SET CurrentDir=%~dp0
java -jar %CurrentDir%paper-1.16.5-576.jar

OR

"path to java bin" -jar %CurrentDir%paper-1.16.5-576.jar

**Comment by Sanaan01** [comment]
![image](https://user-images.githubusercontent.com/81903566/113518034-6953ed00-958c-11eb-8566-91682a165923.png)
I get this error how do i point it directly to the .bat

**Comment by Sanaan01** [comment]
i also tried different variations of the above

**Comment by vincss** [comment]
A first step would be to create a .bat that can be run from any where, then you can try to launch the bat from SSS.

**Comment by Sanaan01** [comment]
Okay ill see if i can do that

**Comment by Sanaan01** [comment]
i fixed it i have a question how do i enable the port to go to bedrock players 19133

**Comment by vincss** [comment]
You just have to modify the config file  sleepingSettings.yml to
bedrockPort: 19133

**Comment by Sanaan01** [comment]
![image](https://user-images.githubusercontent.com/81903566/113558209-e7a1a500-9607-11eb-9d24-b599fff02284.png)
like this right?

**Comment by vincss** [comment]
It's in the  sleepingSettings.yml generated when you start the app for the first time.

**Comment by Sanaan01** [comment]
Its not there for me should i reinstall it

**Comment by Sanaan01** [comment]
while i was reinstalling i got stuck on this error 
![image](https://user-images.githubusercontent.com/81903566/113599873-e85a2b80-9647-11eb-8033-63c73ffb9645.png)

**Comment by vincss** [comment]
Either try with npm ci, or try with the executable. :-)
I think you don't have rights on the directory.

**Comment by vincss** [comment]
Is this fixed ?
