### ISSUE TITLE
plug and mod at this point

### ISSUE THREAD

**Issue by NoobisJ** [vincss/mcsleepingserverstarter#210]
Does anyone know how to add mods and plugins? I mean at this point i got everything. https://www.youtube.com/watch?v=WqvQISpr6-s&ab_channel=TroubleChute when i watched there wasn't a plugin to put it in

**Comment by vincss** [comment]
Which plugins and mods are you talkin about ?

**Comment by NoobisJ** [comment]
I just want to have plug ins and mods cause idk how I want like auto turn off server when no one is on mod I have the jar file already

**Comment by vincss** [comment]
This one ?  https://github.com/vincss/mcEmptyServerStopper 
=> https://github.com/vincss/mcEmptyServerStopper/releases/tag/v1.1.0

just put the .jar in your plugins folder.

**Comment by NoobisJ** [comment]
So I'm trying to ask how to get a plug-in folder

**Comment by vincss** [comment]
In the readme : 
For Fabrik & Forge versions : https://github.com/GHYAKIMA/emptyserverstopper-mod/releases

**Comment by NoobisJ** [comment]
Oh ok thxs I'll try it out
