### ISSUE TITLE
Does this work with a Fabric server?

### ISSUE THREAD

**Issue by Leandrokawa456** [vincss/mcsleepingserverstarter#218]
Hi, I´m kinda new to this, but, does this work for Fabric servers? If not, do I have to install something else or it simply won´t work?

**Comment by spanasiuk** [comment]
@Leandrokawa456, it should work with pretty much any server - make sure to update configs as per the instructions in the readme. Especially the `minecraftCommand` property

**Comment by vincss** [comment]
Hi,
Yes, there is a wiki page for that : https://github.com/vincss/mcsleepingserverstarter/wiki/Sponge-Forge-support

**Comment by vincss** [comment]
@Leandrokawa456 
Hi, is it ok for you ?
