### ISSUE TITLE
[Request] Hold Connection

### ISSUE THREAD

**Issue by SkyKingPX** [vincss/mcsleepingserverstarter#221]
Hello again,
This time I was thinking of the feature like in lazymc. It is similar to your Project, but hasn't as many features as your Project. Because of this I didn't want to switch to it. 

So my Suggestion is that you can set in the config if you want to be kicked on the startup and after that the message will show up or if you want the people to hold the connection an join when the Server is ready.
I hope this could work (also without Linux 😆).

**Comment by vincss** [comment]
Hi,
I think someone already mentioned that, but it will be difficult to do as the connection is managed by https://github.com/PrismarineJS/node-minecraft-protocol for now.
I keep it open just in case.

**Comment by SkyKingPX** [comment]
Ok, but it would be VERY helpful if you could do something with the „Signals“ that don’t work well on Windows

**Comment by SkyKingPX** [comment]
@vincss So you have plans to make the project standalone?

**Comment by SkyKingPX** [comment]
Awww 😞

**Comment by SkyKingPX** [comment]
@vincss

**Comment by vincss** [comment]
> Awww 😞 What is about the other requests? Do you accept them?

Can you avoid spamming ? No the first time I told you.
I'm considering your requests, I'm on another project for now. Maybe when I have more time for this one, and somebody else is interested by those requests.

**Comment by SkyKingPX** [comment]
Sorry, I just thought that you didn’t read the message after I edited it…

**Comment by Jannik44** [comment]
> Ok, but it would be VERY helpful if you could do something with the „Signals“ that don’t work well on Windows

windows is nowhere as relevant as linux for mc server hosting for obvious reasons, i wouldnt even support it at all, just use linux

**Comment by SkyKingPX** [comment]
> windows is nowhere as relevant as linux for mc server hosting for obvious reasons, i wouldnt even support it at all, just use linux

For some people, Windows is better or they just use Windows and can’t just switch to Linux. Why can’t you accept that?

When someone codes Software they should be aware of multiple operating systems.

**Comment by SkyKingPX** [comment]
I am not here to discuss anything. I am here because i have a Suggestion/Problem, that has to be solved.
