### ISSUE TITLE
[Rpi Ubuntu] Unexpected token in a node_module

### ISSUE THREAD

**Issue by lmiquel** [vincss/mcsleepingserverstarter#223]
Hi, I'm trying to set this up for my fabric server that is running on a raspberry pi (ubuntu server os, I used Pinecraft to install the server) and I'm having this error when I run npm start. Anyone knows what is it and how to fix it please? thank you
![image](https://github.com/vincss/mcsleepingserverstarter/assets/59071157/d189d394-ac4f-48d4-a4af-ad29e917733a)

**Comment by vincss** [comment]
Hi,
It may be easier to use the binaries, arm64 for rpi, check the architecture of your distribution with "uname -a" .
https://github.com/vincss/mcsleepingserverstarter/releases

Did you install the packages with "npm ci" ?

**Comment by lmiquel** [comment]
It works fine using the binaries, thank you so much!

**Comment by lmiquel** [comment]
Oh and yes I did install all the packages with npm ci when I had the error sorry for not saying that sooner
