### ISSUE TITLE
NPM Erorr

### ISSUE THREAD

**Issue by Lockstar26** [vincss/mcsleepingserverstarter#228]
So, to preface I'm running all of this on a window 10 VM....Dont even know if its possible

I have a 1.20.1 Paper mc server. 

I followed this guide to install MCsleepingserverstarter. https://www.youtube.com/watch?v=WqvQISpr6-s 

It kinds of sucks, the only step I can't get past is the last one where you open cmd in your server folder and run NPM install and npm start. 

installed JSnode without issues. so unsure of what's going on.

The install comes back with 5 moderate issues as shown: 
![image](https://github.com/vincss/mcsleepingserverstarter/assets/159747837/596c4d0d-698f-4679-a50b-3d98f96d539e)

![image](https://github.com/vincss/mcsleepingserverstarter/assets/159747837/aef7c63f-00e5-4669-84fc-6ee063386937)

And the npm start errors like crazy as shown:
![npm start 1](https://github.com/vincss/mcsleepingserverstarter/assets/159747837/204fceaa-6055-41b7-baa9-1fdefe4b30a3)

![image](https://github.com/vincss/mcsleepingserverstarter/assets/159747837/3c2b9a5a-fd46-4874-ab53-7aabbdb29a03)

has anyone experienced this before or know how to fix or wtf im doing wrong.

**Comment by vincss** [comment]
Hi !
did you read the readme at the top of this github ? Did you try with the binaries ?

**Comment by Lockstar26** [comment]
Hi Dude,

I did use the .exe and it worked but couldn't find a way to change the ram usage. Is there a way?

**Comment by vincss** [comment]
Which ram usage are you talking about ? 
For the MC server it's in the parameter : <html>
<body>

minecraftCommand
--


<br class="Apple-interchange-newline">
</body>
</html>
