### ISSUE TITLE
Getting many errors

### ISSUE THREAD

**Issue by SkyKingPX** [vincss/mcsleepingserverstarter#238]
Since I changed the restartDelay I am getting errors for insufficient memory. That can't be true, because I have 32GB RAM and the Server uses only 30GB.
These errors are Spamming and creating thousands of files. Here is one of the 8000:
[hs_err_pid16380.log](https://github.com/vincss/mcsleepingserverstarter/files/14545324/hs_err_pid16380.log)
![Screenshot 2024-03-08 211343](https://github.com/vincss/mcsleepingserverstarter/assets/95442431/573c0148-e4ee-497b-a040-e4c23e73f785)

[latest.log](https://github.com/vincss/mcsleepingserverstarter/files/14545327/latest.log)
[sleepingServer.log](https://github.com/vincss/mcsleepingserverstarter/files/14545328/sleepingServer.log)

What is going wrong and how to fix it?

**Comment by Jannik44** [comment]
> the Server uses only 30GB.

there is something horribly wrong when your server uses 30gigs of ram, if you have only 2GB ram extra its certain that you are out of ram

**Comment by SkyKingPX** [comment]
But it worked for a year

**Comment by SkyKingPX** [comment]
I tried it with 25GB, but it is still not working. There has to be something wrong...

**Comment by Jannik44** [comment]
why do you even set it to 25GB? there is no valid reason to my knowledge to use this much ram for a single mc server, too much allocated ram will significantly hurt your performance


try again with like 8gb ram and start from there

**Comment by SkyKingPX** [comment]
> too much allocated ram will significantly hurt your performance

The performance is great when 5 players are playing 

> try again with like 8gb ram and start from there

I won’t
