### ISSUE TITLE
MOTD (Server name) Color codes

### ISSUE THREAD

**Issue by Its7up** [vincss/mcsleepingserverstarter#24]
Good job on the script! 

An issue I encountered is that when using the Linux binary the serverName: in the .yml file gets escaped by backslashes, so color codes that would be used in the server.properties file, like "\u00A7d", get displayed directly when a person pings the server. They should be broadcasted as is without escaping so that the client renders the colors and formats. I don't know if this is an easy change to make given the protocol you use.

**Comment by vincss** [comment]
When I set the 
serverName: "\u00A7d SleepingServer, waiting for his prince..."
It set the color right
![image](https://user-images.githubusercontent.com/2254806/117954876-bf4c4b00-b317-11eb-854f-2c5f9b71b8e7.png)

Am I missing something ?
