### ISSUE TITLE
Uninstalling the program

### ISSUE THREAD

**Issue by EasyCanadianGamer** [vincss/mcsleepingserverstarter#241]
I changed my mind not to use your program, but I have no idea how to remove it since now my server won't open with port 22565. I installed it with the binary. ( I use Ubuntu Linux) Is there a way to remove the program?

**Comment by vincss** [comment]
Hi,
It's a simple executable, there is not need to uninstall anything.
You can configure another port also.

**Comment by EakiTurtle** [comment]
where is the executable located?

**Comment by vincss** [comment]
Hi,
Did you manage to uninstall it ?
