### ISSUE TITLE
cant change picture

### ISSUE THREAD

**Issue by Gaming-Gnome** [vincss/mcsleepingserverstarter#245]
i am running it with binaries, everything works fine as i config except the image, i converted the image in that one site and pasted it in my config and it still looks like
<img width="54" alt="image" src="https://github.com/vincss/mcsleepingserverstarter/assets/140624441/eee92fe6-3a28-4fa2-b50c-539d640ab949">
<img width="904" alt="image" src="https://github.com/vincss/mcsleepingserverstarter/assets/140624441/855e0eba-9312-43f7-b550-6679f970b2db">

**Comment by EakiTurtle** [comment]
The string needs to be enclosed in parenthesis, and also, the image must be converted to a 64x64 pixel size before encoding it.

**Comment by vincss** [comment]
It seems that your image is on two lines, did you try to put it in a single line ?
