### ISSUE TITLE
Module "@jsprismarine" missing

### ISSUE THREAD

**Issue by EakiTurtle** [vincss/mcsleepingserverstarter#246]
![image](https://github.com/vincss/mcsleepingserverstarter/assets/108425462/1fbdde86-70f5-4351-8529-0fd3d7276d64)
This is a screenshot of the errors.
I cannot set up my minecraft server because jsprismarine seems to be missing; thing is, I'm running a java server and don't think I need it. I'm not sure how to fix it.
I've tried to delete sleepingBedrock.ts, but there are other files that depend on it, so I don't really want to try and modify everything.

edit: node_module/@ jsprismarine exists within the folders. but the subfolders specified in the errors are not

**Comment by sohdahh** [comment]
ig trying to make a empty node project and install jsprismarine then replace the folder

**Comment by sohdahh** [comment]
wait no just update/install jsprimarine (i did not realise this was in js/ts 💀 )

**Comment by EakiTurtle** [comment]
@sohdahh it doesn't work .. im not sure if i'm doing it as you intended. I was in the minecraft directory and typed "npm update" and "npm update jsprismarine" and "npm install jsprismarine" before trying to start the server

**Comment by vincss** [comment]
Did you read the readme ? 
https://github.com/vincss/mcsleepingserverstarter?tab=readme-ov-file#-install

**Comment by EakiTurtle** [comment]
I did read the readme. 
... I also ended up using binaries instead, which ended up working.

**Comment by vincss** [comment]
If you do a "npm ci", you should not have any trouble with packages version.
