### ISSUE TITLE
How do you change the Sleeping Server Icon?

### ISSUE THREAD

**Issue by NaythanYT** [vincss/mcsleepingserverstarter#25]
I'm wondering how do I change the Sleeping Server Icon, as I'm confused on how to do so. Do I just update the sss.ico file or do I change it in sleepingSettings.yml?

**Comment by vincss** [comment]
Hi !
You need to set it in the config file as a base64 encoded image :
favIcon: data:image/png;base64,iVBORw0KGgoAAAAN...

https://www.base64-image.de/

**Comment by NaythanYT** [comment]
> Hi !
> You need to set it in the config file as a base64 encoded image :
> favIcon: data:image/png;base64,iVBORw0KGgoAAAAN...
> 
> https://www.base64-image.de/

Ah, ok. Thank you!
