### ISSUE TITLE
Getting peeks from random ip-adresses?

### ISSUE THREAD

**Issue by SnelleJaapie** [vincss/mcsleepingserverstarter#251]
Since I got the plugin to work, I have been getting these random pings for my server every 5 minutes or so. 
The IP's are not random, every hour or so the same set of IP's is pinging my server/
![image](https://github.com/vincss/mcsleepingserverstarter/assets/79839202/c12067f1-6c01-4cec-8648-1cc517cfa85f)

What are those and why is this happening?

No I have not shared my IP on a forum or whatever, just set up a server for my friends and I. It's also too consistent to be peeked at by players.

**Comment by AnnsAnns** [comment]
It's actually quite simple, people have found out that Minecraft servers are really easy to find so people have started creating automatic pinging setups to find servers with no whitelist to grief (Or even to properly warn people abou this) - That's ust how the web works nowadays.

**Comment by SnelleJaapie** [comment]
@AnnsAnns 
Makes sense. Didn't think it would be that obvious haha. I didn't have a whitelist enabled yet but i'll be doing that shortly just in case. Thanks!
