### ISSUE TITLE
1.20.6

### ISSUE THREAD

**Issue by ckegels** [vincss/mcsleepingserverstarter#256]
![mcerror](https://github.com/vincss/mcsleepingserverstarter/assets/30844154/304744fc-8838-4332-8ecb-a8efb5c10f3d)
Getting errors when using with 1.20.6

Anybody got it to work?

Temp solution that seems to work for now (will try to update if stops working):
set this in your sleep config: useLegacyLogin: true
still pops up an error but it does boot up the server.

**Comment by vincss** [comment]
There is already tickets for that: 
https://github.com/vincss/mcsleepingserverstarter/issues/247
