### ISSUE TITLE
Run on Raspberry Pi ( wake up a distant computer )

### ISSUE THREAD

**Issue by TheGrandJaggard** [vincss/mcsleepingserverstarter#260]
Hi,

I'm wondering whether it's possible for me to run this on a raspberry pi, which will then start the server running on my PC.

Can I maybe change the `minecraftCommand` setting to run a script which will run the server on the PC? I really want it to be able to wake up the computer from sleep when somebody tries to connect.

Thanks,
Jaggard

**Comment by vincss** [comment]
Hi,
It would be possible using something like Wake-On-Lan, but it's a very customized script that you would have to do : 
https://en.wikipedia.org/wiki/Wake-on-LAN

**Comment by TheGrandJaggard** [comment]
Do you know where I could find or how I could write such a script?
How would the sleeping server starter know when to start up again?

**Comment by vincss** [comment]
I guess Google is your friend, and never did that before : 
https://www.google.com/search?q=linux+script+wol&rlz=1C1GCEB_enBE1087BE1087&oq=linux+script+wol&gs_lcrp=EgZjaHJvbWUyBggAEEUYOTIGCAEQRRhA0gEINTI1OWowajeoAgCwAgA&sourceid=chrome&ie=UTF-8

Maybe in the script you could do something that wait for the server to be up and then for it to shutdown. 
Good luck

**Comment by vincss** [comment]
How are you doing ? Can I close the issue ?

**Comment by TheGrandJaggard** [comment]
It's really to bad that your program doesn't support this, but I guess you can close this. If I ever find a solution I'll re open the issue to post my solution.
