### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by rehaaaa** [vincss/mcsleepingserverstarter#276]
Hi, i need help

![image](https://github.com/user-attachments/assets/99811100-a998-48dc-9335-03ba2162f3f0)

**Comment by vincss** [comment]
Hi,
Can you please : 

- Be nice and say hi.
- Make at least a title without errors ( not errirs ).
- Write a little description.
- Read the README.md where it says : https://github.com/vincss/mcsleepingserverstarter?tab=readme-ov-file#-manually-install-and-compile
`Launch npm ci`

**Comment by rehaaaa** [comment]
Hey, read the readme twice and still the same errors. 
![image](https://github.com/user-attachments/assets/26176e43-b0c0-4c6b-827e-903852cc8c1f)

**Comment by rehaaaa** [comment]
![image](https://github.com/user-attachments/assets/3744706e-db9f-4914-8081-166a2b047289)
