### ISSUE TITLE
Console commands

### ISSUE THREAD

**Issue by PieterVanBeers** [vincss/mcsleepingserverstarter#28]
Is there a way to input console commands when using this program?

**Comment by vincss** [comment]
Hi !
Yes ! 
When the software launches minecraft, the console is redirected to minecraft input stream.

**Comment by PieterVanBeers** [comment]
Weird, when i try to put in commands it doesn't seem to do anything.

**Comment by vincss** [comment]
Did you enable the web-gui or not ? 
On which system are your running ?

**Comment by PieterVanBeers** [comment]
There is a web gui where i can see if the server is sleeping or not and i
can wake it up.
I tried it on my windows 10 machine before putting it on my windows server
machine.

**Comment by PieterVanBeers** [comment]
i'm also using the exe, not the source code with node.js, i changed nothing
in the config file other than webPort which is now set to 80

**Comment by vincss** [comment]
If you are running on windows and launching the web-ui, the redirection from console can be tricky, maybe you can launch the minecraft server with the GUI in which you can input your commands ? 
minecraftCommand: java -jar paper.jar nogui
=> 
minecraftCommand: java -jar paper.jar

**Comment by PieterVanBeers** [comment]
This works, thank you so much for your help!
