### ISSUE TITLE
Not Today... :(

### ISSUE THREAD

**Issue by Sheefou** [vincss/mcsleepingserverstarter#3]
![capture3](https://cloud.githubusercontent.com/assets/7604544/14079127/5f9dcab0-f4c9-11e5-92d6-f81216e05882.PNG)

Fun

**Comment by vincss** [comment]
Sorry I didn't see this, try to do
npm update 
and write the wright version of your client in the config file, for now it should be 1.9.2.

**Comment by vincss** [comment]
No news about it...
