### ISSUE TITLE
Port forwarding / Chunk size read/unread issues

### ISSUE THREAD

**Issue by JayAnderson360** [vincss/mcsleepingserverstarter#35]
Hi. I've been building a MC server for a while now and I've found this video https://youtu.be/WqvQISpr6-s on an auto start and stop MC server which references ur work on the mcsleepingseverstarter which works great with the server I'm building. I followed the tutorials in the video, i even downloaded ur .exe file in the github to run my server. it works great!!!!  except for one minor issue.  The issue is when i began to port forward my server . my router began to start sending  "large chunk sizes...." (i dunno what the proper terminology is called...sorry) to the MC sleeping server starter.... causing it to show some errors and crashsing my server after a few pings....the weird part is....if i were to not use the auto start and stop MC server function and ran my server 24/7 like other general MC server.... its fine.... so i assume that my port forwarding  setup  is only affecting the MC sleeping server function. any help would be greatly appreciated.

image link of the problem (https://media.discordapp.net/attachments/788922845534748768/852167439634137098/Screenshot_5.png)
![image](https://user-images.githubusercontent.com/80225216/121406003-3fee7d80-c990-11eb-98f7-f46632e2eb25.png)

I'm very new to port forwarding....I've previously used radmin (https://www.radmin-vpn.com/) to simulate LAN connectivity for people to play on my server. i hope you can help. i would be happy to send you my router specs and setup as well but i'll wait for a reply in discord (Err̔̏̊or#3500)

**Comment by JayAnderson360** [comment]
as for the log folder is does not show the issue, just the pings of the handshake
[sleepingServer.log](https://github.com/vincss/mcsleepingserverstarter/files/6625964/sleepingServer.log)

**Comment by JayAnderson360** [comment]
update on the issue....manages to catch the error mid crash.... sending a pic
![Screenshot (17)](https://user-images.githubusercontent.com/80225216/121681808-d4babd80-caed-11eb-9d2a-7286ee30d949.png)

ERR_OUT_OF_RANGE....Does that means anything?

**Comment by vincss** [comment]
Hi ! 
Very sorry to hear about those issue, but there are directly happening inside the library that I'm using so I cannot do much about it. :( I will check for a workaround if I can.

**Comment by JayAnderson360** [comment]
Take ur time man. looking forward to the patch :)

**Comment by carlni2008** [comment]
hello, i think my problem might be related to this: A Prince has taken a quick peek. [handshaking_1.16.5].
I am wondering if the server can start when "A Prince has taken a quick peek. [handshaking_1.16.5] this happens? Rather than doing nothing

**Comment by vincss** [comment]
No because it's when someone is pinging the server which can happen quite often.
