### ISSUE TITLE
1.17 Support

### ISSUE THREAD

**Issue by Dogepot2** [vincss/mcsleepingserverstarter#38]
Currently it's not working correctly with Minecraft version 1.17, I just cloned the repo to make sure I had every file updated.

When closing my spigot server the process gets stuck at the end and after pressing Ctrl+C this shows up:
![image](https://user-images.githubusercontent.com/43354165/121837134-e7c2be80-cca2-11eb-905d-2c2143cc8433.png)

I've been using your project a lot and for while now so thank you for all the work you've put into it <3

**Comment by vincss** [comment]
Hi !
It's still working in progress in the minecraft-protocol lib that I'm using, so we have to wait for their next release (or beta) : 
https://github.com/PrismarineJS/node-minecraft-protocol#readme

In the meantime, you can use the web version to wake your server up, juste set the option : 
webPort: 25566
=> http://localhost:25566/
And use the button to wake the server up : 
![image](https://user-images.githubusercontent.com/2254806/121856029-52501a80-ccf4-11eb-8df5-715fbd0d55b2.png)

**Comment by Dogepot2** [comment]
I can actually wake the server directly from the game, but when shutting down the server it bugs out without it ever going back to the sleeping state. Is it okay for me to leave this issue open until 1.17 is supported? 

Thank you again for all your work and attention to the project ❤️

**Comment by vincss** [comment]
Yes of course, so if people are asking the same question, they might find this.

**Comment by pablohess** [comment]
Are there known issues with 1.17?

**Comment by Dogepot2** [comment]
Server says 1.16.5, but aside from that, everything is now working as it should, at least with Java.
