### ISSUE TITLE
Can't use aliases in Linux

### ISSUE THREAD

**Issue by linkthehero1234** [vincss/mcsleepingserverstarter#39]
I setup the cmd macro `java11` to the location of my openjdk installation for windows but when I do it in Linux with the alias `java11="java"` setup in `~/.profile`, `~/.bashrc`, and `~/.zshrc` it doesn't work

**Comment by vincss** [comment]
Hi !
I think the issue is related to java installation not SSS. 
Did you log in again after setting the variable to your .bashrc ?
Is it working when you do java -version ?
