### ISSUE TITLE
color code support

### ISSUE THREAD

**Issue by Beastifi3d** [vincss/mcsleepingserverstarter#40]
I might just be stupid here, but can you add color code support. I don't know how to use color codes

My original idea was like this:
![PKKgt3 1](https://user-images.githubusercontent.com/32767771/122352824-aa4b8300-cf79-11eb-8b5d-6cf953f63706.png)

**Comment by vincss** [comment]
Hi !
There was already an opened issue about this, those it help ? 
https://github.com/vincss/mcsleepingserverstarter/issues/24
