### ISSUE TITLE
info: A Prince has taken a quick peek. [handshaking_1.16.5]

### ISSUE THREAD

**Issue by carlni2008** [vincss/mcsleepingserverstarter#42]
The log says "info: A Prince has taken a quick peek. [handshaking_1.16.5]" when people try to connect through Bungeecord. My problem is if there are anyway to make the server start when "info: A Prince has taken a quick peek. [handshaking_1.16.5]" happens instead of doing nothing.

**Comment by carlni2008** [comment]
also, is there a way to disable bedrock support?

**Comment by Beastifi3d** [comment]
> also, is there a way to disable bedrock support?

You can disable bedrock by going into SleepingSettings.yml and setting the BedrockPort to 0

**Comment by carlni2008** [comment]
> You can disable bedrock by going into SleepingSettings.yml and setting the BedrockPort to 0
tHANK YOU
