### ISSUE TITLE
No wakeup message in 1.17

### ISSUE THREAD

**Issue by MrR341-GER** [vincss/mcsleepingserverstarter#43]
when starting the server, the "waking server up, come back in a minute" is not showing up.
Instead it just says: "Connection Lost" -> But it starts anyway and I wrote some pretty neat bash and python scripts with a shelly plug wich starts the whole server (my pc in fact..)

Raspberry pi with server starter and Bungeecord, and pc with servers.

Problem occurs in Java and Bedrock
The "Sleeping Server, Waiting for a prince to come" is still there in java.. (not in Bedrock..)
In Bedrock the Server shows offline, but starts anyway if someone is trying to connect..

So no problem in functionality on 1.17 jjust the messages dont work properly

**Comment by vincss** [comment]
Hi !
You can use the beta that I just made for 1.17.1, the minecraft-protocol package is not release yet, so I used the repo git instead.
Either by using : 

Binary : https://github.com/vincss/mcsleepingserverstarter/actions/runs/1056185355

Source code : https://github.com/vincss/mcsleepingserverstarter/tree/feature/support_1.17.1_beta
git pull
git checkout feature/support_1.17.1_beta
npm ci
npm start

Hope it will work for you !
