### ISSUE TITLE
simply cannot run on 1.17

### ISSUE THREAD

**Issue by Hazri45** [vincss/mcsleepingserverstarter#44]
I did what the tutorial ask to do. I follow every instruction but for some reason it doesnt work. I create a new server from the ground up and it simply doesn't work. When I tried to "npm start" the server, the port isn't listening and it is closed but when i try to open the server the traditional way, it works and the port is opened. I don't know what i did wrong here.
![cmd_chBCg0bsaf](https://user-images.githubusercontent.com/52308727/124209868-f7ecf180-db1c-11eb-9c95-12f66ff66fb1.png)
![javaw_5SVoXEy8UW](https://user-images.githubusercontent.com/52308727/124209877-fb807880-db1c-11eb-9043-e6641e5ed97f.png)
![javaw_n4uCuKOfTI](https://user-images.githubusercontent.com/52308727/124209899-076c3a80-db1d-11eb-8473-3b317e10d52f.png)

**Comment by Beastifi3d** [comment]
Yeah, I don't think it works on 1.17. Not sure, though.

**Comment by Hazri45** [comment]
> Yeah, I don't think it works on 1.17. Not sure, though.

Thanks for the quick reply. Sorry if i comes off as harsh. i will keep experimenting. Thanks again

**Comment by Beastifi3d** [comment]
> > Yeah, I don't think it works on 1.17. Not sure, though.
> 
> Thanks for the quick reply. Sorry if i comes off as harsh. i will keep experimenting. Thanks again

No worries, I have email subscription and it gives me a notification everytime something happens.

**Comment by krystlerc** [comment]
1.17 works for me. But 1.17.1 does not.

**Comment by vincss** [comment]
Hi !
You can use the beta that I just made for 1.17.1, the minecraft-protocol package is not release yet, so I used the repo git instead.
Either by using : 

Binary : https://github.com/vincss/mcsleepingserverstarter/actions/runs/1056185355

Source code : https://github.com/vincss/mcsleepingserverstarter/tree/feature/support_1.17.1_beta
git pull
git checkout feature/support_1.17.1_beta
npm ci
npm start

Hope it will work for you !
