### ISSUE TITLE
Can´t turn on the server

### ISSUE THREAD

**Issue by Nadiecer0** [vincss/mcsleepingserverstarter#49]
When i try to start the server it starts, but when anoter one with non bought minecraft tries to open the server it pops this message ![imagen](https://user-images.githubusercontent.com/88974557/129480810-fcfe652a-34c8-4b1e-a8ea-2bbae640f405.png)****

**Comment by vincss** [comment]
Did you set the mode to offline in your settings file ?
https://github.com/vincss/mcsleepingserverstarter/blob/master/sleepingSettings.yml#L8
