### ISSUE TITLE
Is this thing on??

### ISSUE THREAD

**Issue by LividJava** [vincss/mcsleepingserverstarter#5]
Heyo, i know i didn't respond in my last few tickets and its been some time, but is this being planned on updating to the new versions?? Attempts to use for 1.15.2 have been foiled thanks again.

**Comment by vincss** [comment]
Hi, it's seen awhile, I will have a look when I've some spare time for that. ;-)

**Comment by vincss** [comment]
Hi ! I updated the thing for 1.15.1.
But for 1.15.2, the underlying package hasn't been release yet :
https://github.com/PrismarineJS/node-minecraft-protocol
