### ISSUE TITLE
[Suggestion] Support color formatting Java

### ISSUE THREAD

**Issue by Rysanlos** [vincss/mcsleepingserverstarter#51]
On java edition you can add color and other text modification inside of the modt, but when I use them on mcsleepingserverstarter, it's not supported, they are showed plain text instead of colors.
Here to see what I'm talking about, column "MOTD color codes": https://minecraft.tools/en/color-code.php

Is it possible to add support for it? Thank you!

**Comment by vincss** [comment]
Hi !
It is supposed to work : 
https://github.com/vincss/mcsleepingserverstarter/issues/24

Can you give me an example of non-working serverName ?

**Comment by Rysanlos** [comment]
It's doing this:
![image](https://user-images.githubusercontent.com/22010386/130093658-cc6929ed-04ea-4220-a692-17adf900e19d.png)
But then I realized you are using " " after serverName in your #24 example, and it's working like it should now.
There is not " " in your default config file so it's confusing.
Thank you anyway :)

**Comment by vincss** [comment]
You're right ! I will add them :-)
