### ISSUE TITLE
My friend cant wake up the server 

### ISSUE THREAD

**Issue by Yond3rBoy** [vincss/mcsleepingserverstarter#52]
i now have a problem why when it sleep i join can open but why my server sleep it not work for my friend it just 'cant correct to the server'
pls help me fix and thanks

**Comment by vincss** [comment]
Hi !
Which client is your friend using ?
What is different from yours ?
Can you provide the logs ?

**Comment by Yond3rBoy** [comment]
can help pls

**Comment by iwa** [comment]
after some tests, i can't reproduce your issue
its hard for us to fix your issue as its coming from your end and not ours, you might have misconfigured something between the versions, the server and SleepingServerStarter
sorry that we can't go further, you should try to re-check all your configs, see if you match the correct versions and maybe try to see if you're router is configured well
