### ISSUE TITLE
[Idea Suggestion] Discord webhook on start

### ISSUE THREAD

**Issue by chubby1523** [vincss/mcsleepingserverstarter#58]
Would it be possible to add a simple option for a discord webhook which would just push who started the server to discord?

**Comment by iwa** [comment]
that could be a thing yeah, what do you think @vincss ?

**Comment by vincss** [comment]
Yes, it's a nice idea ! :-) 
I didn't play with Discord bot yet.

**Comment by vincss** [comment]
Hi !
We came up with a solution, can you give it a try and tell us if it's ok for you :

1. You need to use the binary or the latest version from the feature branch : https://github.com/vincss/mcsleepingserverstarter/actions/runs/1417790854 or https://github.com/vincss/mcsleepingserverstarter/blob/feature/discord_notification/sleepingSettings.yml#L21 
2. You need to create a webhook on your discord channel : https://support.discord.com/hc/en-us/articles/228383668-Intro-to-Webhooks
3. Set the discordWebhookUrl setting with the url or your web-hook. Uncomment this line or add it to the generate settings file  ( https://github.com/vincss/mcsleepingserverstarter/blob/feature/discord_notification/sleepingSettings.yml#L21 ). 
4. Start the app as usual. :-) 
5. Tell us if it's ok, or if you have other ideas !

Thanks !

**Comment by iwa** [comment]
feature implemented in #63
