### ISSUE TITLE
quit command starts server

### ISSUE THREAD

**Issue by AgentRobo** [vincss/mcsleepingserverstarter#64]
When starting programm, and wanting to stop it, the quit command does stop the programm but starts the server.
Then if trying to stop the server, the programm starts up again.

**Comment by vincss** [comment]
Hi !
Did you try with ctrl+c ?

**Comment by AgentRobo** [comment]
Yeah that worked! Thank you a lot, would help if that would be addet to the start

**Comment by vincss** [comment]
@iwa can you document this ? :-D

**Comment by iwa** [comment]
done, even though its not really program-related but more a system shortcut
