### ISSUE TITLE
unsupported protocol version: 1.18

### ISSUE THREAD

**Issue by SylveonBottle** [vincss/mcsleepingserverstarter#67]
`error: Something bad happened. unsupported protocol version: 1.18`

**Comment by vincss** [comment]
Hi !
We are based on : https://www.npmjs.com/package/minecraft-protocol

Which is not yet compatible with MC 1.18/

**Comment by pablohess** [comment]
They released version 1.29.0 which works with 1.18. Not sure if it's also working with 1.18.1.

**Comment by vincss** [comment]
A new version has been released, can you give it a try ? 
https://github.com/vincss/mcsleepingserverstarter/releases/tag/v1.1.1_1.18.1

**Comment by pablohess** [comment]
"Something bad happened. unsupported protocol version: 1.18.1"

**Comment by vincss** [comment]
My bad, the tag was wrongly create, can you give it another try ?
https://github.com/vincss/mcsleepingserverstarter/releases/tag/v1.1.1_1.18.1

**Comment by pablohess** [comment]
It's working so far. Stopper is also working.
