### ISSUE TITLE
sleepingserver crashes after Minecraft server goes to sleep.

### ISSUE THREAD

**Issue by sebasdt** [vincss/mcsleepingserverstarter#68]
For a while I'm running 4 servers and working wonderfully.
Every so often when a server shuts down and tries to go to sleep sleeperstarter crashes and takes that cmd instance with it.

This also means it just ignores pause command and its almost impossible to see what the cause was.

I've been trying for awhile to figure out what it could be.
Also every server has different rcon/query and server ports.

bat startup script:
`
@ECHO OFF
timeout /t 20
:start
npm start
pause
goto start
pause
`

**Comment by vincss** [comment]
Hi !
You don't see any relevant information in minecraft's log or SleepingServer's log ? Can you post them ?

**Comment by sebasdt** [comment]
oh yes sorry,
The Minecraft log looks normal to me. take a look yourself:  (btw logs are all the same.)
https://pastebin.com/LQCRV65Y


I did take a better look at the sleeperserver's logs and it seems to be inconsistent where it crashes. also, more than I originally thought. : [sleeperserver logs](https://pastebin.com/36wPhxZU)
one thing to point out, at some point a ping bot found my server and constantly was pinging the server.


sadly I'm not finding in the log anything directly pointing to what the problem could be.

**Comment by sebasdt** [comment]
SO the bug finaly clearly accured on one of my servers:
It seems like if 2 players try to join at the same time while sleeperserver tries to startup the minecraft server, thats when things go wrong.

Server sleeper logs
https://pastebin.com/F2PWQeWM

minecraft server logs
https://pastebin.com/dfv6pxP4

Im sorry for my last post it was not up to the normal standard.

**Comment by vincss** [comment]
I'm trying to reproduce the crash but didn't manage to reproduce for now.
There is no clear indication of what's wrong in the logs.
Do you have the web-server enabled ? (from the logs, it doesn't seem to be enabled.)

**Comment by sebasdt** [comment]
>I'm trying to reproduce the crash but didn't manage to reproduce it for now.

The bug is a bit stubborn. It doesn't happen to me if I join alone. It only occurs when different two players or more try to join at the same time. 

> There is no clear indication of what's wrong in the logs.

I've read the sleeper-server log a little better. Here are my thoughts on what could be happening. Grab a small drink and strap in. ;-)

**From lines 38 to 45:** 
Two players join a few seconds after each other. 

**Player 1:**  Triggers the server startup and receives best regards message
**Player 2:**  starts the server up too but can't because player 1 already did it. Also still receives best regards message. (triggering the bug later on)
** Sleeper server stops and Minecraft server starts up after 5 min shuts down**

**From line 56**
I think here is where the bug occurs.
First, the sleeper server wakes up. Then wakes the Minecraft server immediately up without a timeout and anyone asking it to startup. 
It could be happening because the startup flag of player 2 is still set. 

After the Minecraft server shuts down, sleeper-server somehow ain't able to wake up/startup and crashes.


> Do you have the web-server enabled? (from the logs, it doesn't seem to be enabled.)

Nope, I don't have it enabled.

**Comment by sebasdt** [comment]
Hi!

I've got a quick update on how it's going.
Today  I went bug hunting with my friends. Now I'm sure it only occurs when two or more players join somewhat simultaneously.

After the previous Minecraft server has shut down, the sleeper server immediately stops and starts up the Minecraft server again. It does this until some event causes it to crash.


Here below is the serversleeper log, with the bit where serversleeper crashes.
https://pastebin.com/dUi8Qt6u

**Comment by sebasdt** [comment]
Bump

**Comment by vincss** [comment]
Did you try with the binary version ?

**Comment by sebasdt** [comment]
Yeah sure! I will take a look later tonight

**Comment by sebasdt** [comment]
hey man! sorry for taking so long to reply but it seems like the bug is fixed!
If it happens again I'll say it!
