### ISSUE TITLE
How can i update to the newer version?

### ISSUE THREAD

**Issue by sebasdt** [vincss/mcsleepingserverstarter#70]
hello!
I saw that you updated to 1.18.1, and I'm not sure how I can update it.

The thing is I dont want to do a fresh server install.

**Comment by vincss** [comment]
If you are using the binary, just overwrite the existing one with the new one and you're good to go !
If you are using it from code, just do : 
git pull
npm ci
npm start

**Comment by sebasdt** [comment]
thank you.

downloaded the latest version and sadly if i try to start the sleeper server I get this error:
![image](https://user-images.githubusercontent.com/67417070/146526949-67efb8b6-023a-409b-913c-c0285af70d86.png)

I updated to java 17 and nodejs.

Im using these files below, since the tutorial video is a little outdated at this point. 
![image](https://user-images.githubusercontent.com/67417070/146527422-e3f8c643-3376-4640-9cfa-bf73b1a0d2df.png)

**Comment by vincss** [comment]
It's weird because you tsconfig.json seems to be there.
Maybe give a try with the binary, it should be simpler.

**Comment by sebasdt** [comment]
what do you mean with the binary?
sleepingServerStarter.exe?

**Comment by sebasdt** [comment]
Thank you!
it with the .exe it was way simpler and faster.
also worked without any hassle. 
btw the way you showed in the tutorial video should always work. I like it very much.

**Comment by vincss** [comment]
I didn't made the video, it's someone else, I found it out by luck.

**Comment by sebasdt** [comment]
Oh what a luck then!
I said nothing then.
