### ISSUE TITLE
I cant use sleeping server starter.run

### ISSUE THREAD

**Issue by Swapneel665** [vincss/mcsleepingserverstarter#71]
Error : bash: ./sleepingServerStarter.run: No such file or directory

It is giving me this message when I try to use the command

./sleepingServerStarter.run

Linux localhost 4.14.117-perf+ #1 SMP PREEMPT Mon Oct 25 00:28:34 CDT 2021 aarch64 aarch64 aarch64 GNU/Linux

I am using termux
Server files: https://drive.google.com/folderview?id=1WuMyMWpyEwm6VI7dp308FkF2EGVT01Qe

**Comment by vincss** [comment]
It's an aarch64 os, it's not compatible with the usual x86_x64 architecture (in which the binary are). I will have a look if something is possible.

**Comment by Swapneel665** [comment]
Oh I see np

**Comment by vincss** [comment]
Unfortunately building binary for arm64 doesn't seems to work with pkg : 
https://github.com/vincss/mcsleepingserverstarter/runs/4597104423?check_suite_focus=true#step:5:39
