### ISSUE TITLE
Error when trying to start the script

### ISSUE THREAD

**Issue by TheDanniCraft** [vincss/mcsleepingserverstarter#72]
I getting this error when trying to run the script with `npm start`:
![60BCD1C4-D007-4B99-970A-99DA7114BCDC](https://user-images.githubusercontent.com/66677362/148324278-be3eea7c-21cb-4449-bdcf-74dbaba0b638.jpeg)
 
**Node.js Version:** 16.13.1
**Server OS:** Ubuntu 20.04.03 LTS
**Gameserver:** Spigot 1.18

**Comment by vincss** [comment]
Hi !
It should try to write something in the /root/ folder.
Where did you launch it from ?
Did you do a "npm ci" before the "npm start" ?

Did you try with the binary ?

**Comment by TheDanniCraft** [comment]
> Where did you launch it from ?

From a pufferpanel server(But installed manualy because your template is docker based and my VM can't use Docker.)

> Did you do a "npm ci" before the "npm start" ?

Firstly no(followed [this](https://www.youtube.com/watch?v=WqvQISpr6-s) tutorial. But later I ran `npm ci` but this also doesn't fix it) 

> Did you try with the binary ?

Currently no, but I will try it

**Comment by vincss** [comment]
I didn't try the pufferpanel, it's @dada513 who wrote it, maybe he can help.

**Comment by dada513** [comment]
> > Where did you launch it from ?
> 
> 
> 
> From a pufferpanel server(But installed manualy because your template is docker based and my VM can't use Docker.)
> 
> 
> 
> > Did you do a "npm ci" before the "npm start" ?
> 
> 
> 
> Firstly no(followed [this](https://www.youtube.com/watch?v=WqvQISpr6-s) tutorial. But later I ran `npm ci` but this also doesn't fix it) 
> 
> 
> 
> > Did you try with the binary ?
> 
> 
> 
> Currently no, but I will try it

While I did make that template with docker in mind, there's nothing stopping you from running it using the standard mode. There should be no issues

**Comment by dada513** [comment]
Your manual install issue is definitely something up with your permissions

**Comment by dada513** [comment]
Also it seems the binary names have been changed and it has been fixed, so you may have to re-create the server with the updated template

**Comment by vincss** [comment]
Yes I did rename the executables, and forget to update the pufferpanel. Now it should be ok.

**Comment by iwa** [comment]
> Your manual install issue is definitely something up with your permissions

+1

i know there are some issues with running `npm install` as root (things with caches and stuff like that)
in general, you should avoid installing and running everything as root, create a new user with sudo privileges and run everything from this user

**Comment by dada513** [comment]
Especially since pufferpanel uses the pufferpanel user, and not root

**Comment by TheDanniCraft** [comment]
Using the pufferpanel template fixed the error.
But the emptyserverstopper pluggin isn't included at install. I don't know if it's supposed to be like this, but I'll you know 

Thanks for the help

**Comment by dada513** [comment]
It is included, something must’ve gone wrong
