### ISSUE TITLE
The mcsleepingserverstarter appears to have turned itself off

### ISSUE THREAD

**Issue by Manic137** [vincss/mcsleepingserverstarter#76]
As you know, you've helped me quite a bit, but I might have found a new issue. I'm not sure what happened as I had my server online for quite a few hours and it had gone offline through the EmptyServerStopper plugin on its own in that time, and after those few hours someone had tried to turn the server on. I was on at this time and wanted to test this. They are on Bedrock, and well it seemed to not turn the server on. Initially, I thought that it was an issue with Bedrock, but looking back at the mcsleepingserverstarter file after reopening the "start.sh", it had a port for Bedrock, I then prompted that someone to try connecting the server again, and it finally worked. My conclusion is that somehow the mcsleepingserverstarter turned itself off, is there I could add to the "start.sh" to prevent it from dying on its own?

**Comment by Manic137** [comment]
Update #1: I have tested the server myself to diagnose what the actual problem actually is. It turns out that after the server wakes itself up from being offline through mcsleepingserverstarter and then turns off through EmptyServerStopper, the mcsleepingserverstarter doesn't realize this and still thinks the server is online. The script was still outputting "... Server is running ..." over and over despite the server being offline.

**Comment by Manic137** [comment]
@vincss Why did you close the issue? It has not been resolved

**Comment by vincss** [comment]
Because it's related to the other one , in which one I added a comment : 
https://github.com/vincss/mcsleepingserverstarter/issues/73#issuecomment-1019433571

**Comment by Manic137** [comment]
> Because it's related to the other one , in which one I added a comment : [#73 (comment)](https://github.com/vincss/mcsleepingserverstarter/issues/73#issuecomment-1019433571)

Technically it was related to issue #74, but despite being related, is a different issue. I do not know how to automatically restart the "mcsleepingserverstarter" service after the server is turned off, as after the server shuts itself down, the service still thinks it is running. This makes the server "unavailable" rather than the expected "sleeping". I hope you can help
