### ISSUE TITLE
After server is automatically turned off by EmptyServerStopper, mcsleepingserverstarter doesn't turn it back on

### ISSUE THREAD

**Issue by Manic137** [vincss/mcsleepingserverstarter#77]
I do not know how to automatically restart the "mcsleepingserverstarter" service after the server is turned off from being empty. As after the server shuts itself down, the service still thinks it is running. This makes the server "unavailable" rather than the expected "sleeping", "mcsleepingserverstarter" outputs "... Server is running ..." despite the server being off and unavailable.

**Comment by vincss** [comment]
Stop creating issue not related to the software itself.
It's specific to your installation.
I'm already kind enough to give you some support.
Only reply on the same issue, so we have the history of your installation at least : 
https://github.com/vincss/mcsleepingserverstarter/issues/73

**Comment by Manic137** [comment]
> Stop creating issue not related to the software itself. It's specific to your installation. I'm already kind enough to give you some support. Only reply on the same issue, so we have the history of your installation at least : #73

My bad, I figured they were different issues and I should make new ones. I'm sorry
