### ISSUE TITLE
Backup compatibility [Suggestion(?)]

### ISSUE THREAD

**Issue by JorgeLara23** [vincss/mcsleepingserverstarter#78]
First of all, the plugin is already amazing, I love it.

Maybe it is already possible, I am very new with servers and also github.
Is there a way to start the server always at a certain hour? 
So if you have a backup plugin that works for example at 3:00 AM, you start it always at 2:55 and have the EmptyServer stopper to stop at 15min.
As I said I am not really used to servers, but it doesn't seem like a very difficult thing to add and it would be great.

**Comment by vincss** [comment]
Hi !
This is not the purpose of this plugin sorry.
I would suggest you to use something like cron or other scheduling  mechanisms : 
https://opensource.com/article/17/11/how-use-cron-linux

**Comment by JorgeLara23** [comment]
Thank you, I am looking into it, I am trying to execute the server using "java -Xmx12g -Xms4g -jar papermc1_18_1.jar nogui" but if it is active obviously you can't do it becouse it is already open, but if it is sleeping it also says that I cant becouse of the port already been used.
Do you know if there a command to say the npm to execute the minecraft server if it is not already open so I can make an script with it?

**Comment by JorgeLara23** [comment]
Thank you, I am looking into it, I am trying to execute the server using "java -Xmx12g -Xms4g -jar papermc1_18_1.jar nogui" but if it is active obviously you can't do it becouse it is already open, but if it is sleeping it also says that I cant because of the port already been used.
Do you know if there is a command to say the npm to execute the minecraft server if it is not already open so I can make an script with it?

**Comment by JorgeLara23** [comment]
Thank you, I am looking into it, I am trying to execute the server using "java -Xmx12g -Xms4g -jar papermc1_18_1.jar nogui" if it is active obviously you can't do it becouse it is already open, but if it is sleeping it also says that I cant because of the port already been used.
Do you know if there is a command to say the npm to execute the minecraft server if it is not already open so I can make an script with it?

**Comment by vincss** [comment]
You can try do to a shell script that will look into the process list and launch a process or the other if it's running or not.
https://www.google.com/search?q=ps+grep&rlz=1C1CHBF_frBE971BE971&oq=ps+grep&aqs=chrome..69i57.1124j0j7&sourceid=chrome&ie=UTF-8

**Comment by vincss** [comment]
For backup I used a tool that upload directly the backup on a cloud drive : 
https://dev.bukkit.org/projects/drivebackup

There seems to be a new version : 
https://www.spigotmc.org/resources/drivebackupv2.79519/
