### ISSUE TITLE
FML/Forge is an unsupported protocol

### ISSUE THREAD

**Issue by vhcrack** [vincss/mcsleepingserverstarter#80]
Hi there! I was planning on using this for my Forge server but noticed that it marks the server as a vanilla server.
It still connects fine, but, I was wondering if it was possible to add [minecraft-protocol-forge](https://www.npmjs.com/package/minecraft-protocol-forge) to have added support for modded servers? Thanks!

**Comment by vincss** [comment]
Hi !
Thanks for the suggestion, but it seems there is only the client side of the protocol : 
https://github.com/PrismarineJS/node-minecraft-protocol-forge
