### ISSUE TITLE
Malware abuse

### ISSUE THREAD

**Issue by stefandanzl** [vincss/mcsleepingserverstarter#85]
It seems that mcsleepingserverstarter is abused as a way to install and run malicious software in the directory /tmp/.X69-unix/ which attacks further servers with brute force measures. The malware runs as the mcsleepingserver user.

System: Debian, Spigot 1.18.1, Minecraft Server mostly idle,

**Comment by vincss** [comment]
Hi ! 
I don't create a mcsleepingserver user, which way of install did you use ?

**Comment by stefandanzl** [comment]
I didn't phrase that very well. I run the mcsleepingserver application with "sudo -u mc" and that user named "mc" is the one that ultimately also executes the malware which seems to me that the intruders abuse some weakness in the mcsleepingserver API.
I hope this helps in improving your great work!

**Comment by vincss** [comment]
Do you use the web-api or something ? How do you find out about the malware ?

**Comment by stefandanzl** [comment]
No I meant the ability for external traffic to connect to on the Minecraft port. 
I use "htop" which is a taskmanager in Debian and there you can see that the malware is run as the user "mc" which is usually only used for mcsleepingserverstarter.

**Comment by vincss** [comment]
Any news on this ?

**Comment by stefandanzl** [comment]
I still am having the same reoccurring issue, but I can say for sure that your software does not seem to be the vulnerability.

**Comment by vincss** [comment]
Ok, so I will close it, don't hesitate to come back if you have any news on this.
