### ISSUE TITLE
src/sleepingMCJava.ts - error TS2345- WRONG ARGUMENT

### ISSUE THREAD

**Issue by EinfachZocken-net** [vincss/mcsleepingserverstarter#86]
src/sleepingMcJava.ts:25:36 - error TS2345: Argument of type '{ 'online-mode': boolean; motd: string; port: number; maxPlayers: number; version: string | undefined; beforePing: (reponse: any) => void; }' is not assignable to parameter of type 'ServerOptions'.
  Property 'validateChannelProtocol' is missing in type '{ 'online-mode': boolean; motd: string; port: number; maxPlayers: number; version: string | undefined; beforePing: (reponse: any) => void; }' but required in type 'ServerOptions'.

 25         this.server = createServer({
                                       ~
 26             'online-mode': this.settings.serverOnlineMode,
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
...
 35             // host: '0.0.0.0',
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 36         });
    ~~~~~~~~~

  node_modules/minecraft-protocol/src/index.d.ts:151:3
    151   validateChannelProtocol: boolean
          ~~~~~~~~~~~~~~~~~~~~~~~
    'validateChannelProtocol' is declared here.


Found 1 error in src/sleepingMcJava.ts:25

**Comment by vincss** [comment]
Hi !
Can you tell what have you done ?
It's seems you have used a new version of minecraft-protocol.
