### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by QunatumCrafter** [vincss/mcsleepingserverstarter#87]
I can't find any tutorial for ubuntu Linux and I need help. Once I extract the tar.xz what do I do with those files?

**Comment by vincss** [comment]
Where does this tar.xz comes from ? Did you read the README ? 
https://github.com/vincss/mcsleepingserverstarter#-install

**Comment by QunatumCrafter** [comment]
Ok, I'm so sorry you are very on top of this and an I come along but the tar.xz was node js. I was following a bad tutorial. I still can't find how to use the mcsleepingserverstarter-Linux though, plugins folder?

**Comment by vincss** [comment]
Did you check the video tutorial to have an idea of how it works ? Things are slightly the same under Linux.
https://www.youtube.com/watch?v=WqvQISpr6-s&feature=youtu.be

**Comment by QunatumCrafter** [comment]
do I need to download npm for this to work?
npm ERR! missing script: start

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/blade/.npm/_logs/2022-03-17T21_14_38_752Z-debug.log
 my discord is Quantum_Crafter#5121 can we please vc so i can get this to work :1st_place_medal:

**Comment by vincss** [comment]
You don't need npm or node if you use the binaries.
