### ISSUE TITLE
pterodactyl support

### ISSUE THREAD

**Issue by cicatrice74** [vincss/mcsleepingserverstarter#88]
Can this be adapted to pterodactyl panel system ?

**Comment by vincss** [comment]
Hi ! 
It can be used with pufferpanel : https://github.com/vincss/mcsleepingserverstarter#-pufferpanel
But I didn't try it, and I'm not planning to support pterodactyl.

**Comment by cicatrice74** [comment]
Maybe can u just propose a java version of this so we can use it elsewhere ?

Il Ven 18 Mar 2022, 08:55 Vincs ***@***.***> ha scritto:

**Comment by vincss** [comment]
There was a java version at the start : https://github.com/tustin2121/MCSignOnDoor 
You can restart it if you want. ;-)

**Comment by cicatrice74** [comment]
If i was able do code i would never ask u. I'm onlt trying to understand
why will u never create a version compatible with ptetodactyl panel.

Il Ven 18 Mar 2022, 10:27 Vincs ***@***.***> ha scritto:

**Comment by vincss** [comment]
Maybe ask @[beastksoepic](https://github.com/beastksoepic) for some support and write some doc about it in the wiki.
https://github.com/vincss/mcsleepingserverstarter/issues/90
