### ISSUE TITLE
Unable to change/specify Minecraft server 'version'

### ISSUE THREAD

**Issue by Jefferderp** [vincss/mcsleepingserverstarter#9]
Hello!

Loving this software.

There's one bug I've encountered that I'm unsure how to solve.

My Spigot server is running 1.16.1. However, when the server is off (and mcsleepingserverstarter is watching for port knocks) the server's version reports as **1.16**. Since my players are naturally running 1.16.1, this causes their client to show the server as being outdated/incompatible, as previewed:

![20200719T211617](https://user-images.githubusercontent.com/13530594/87890609-43d68180-ca05-11ea-8279-54a38328c1ef.png)

When attempting to connect to the server anyway (despite the cosmetic error), mcsleepingserverstarter initializes the Spigot server as expected. Once the server has come back online, and I refresh the in-game server list, the game version of course shows "1.16.1" as expected.

When adding the line `version: "1.16.1"` to *sleepingSettings.yml*, the console does report the setting as being picked up:

```
2020-07-19P21.00.42.034 - info: .........................
2020-07-19P21.00.42.035 - info: ... A new story begin ...
2020-07-19P21.00.42.074 - info: .........................
2020-07-19P21.00.42.074 - info: Retrieved settings: serverName=foo, serverPort=25566, loginMessage=Server is waking up! Please reconnect in 10 seconds., serverOnlineMode=true, webPort=0, webDir=plugins/dynmap/web, startMinecraft=1, minecraftCommand=./wake.sh, version=1.16.1
```

...however in-game, the server version still reads as "1.16".

I've also attempted to directly edit [the value in *sleepingSettings.js*](https://github.com/vincss/mcsleepingserverstarter/blob/master/sleepingSettings.js#L17), but the outcome is unchanged.

It appears that the setting is being recognized, but then dropped somewhere down the line. Problem is, I can't see *where* that would be. Was the value "1.16" accidentally hardcoded somewhere?

Thanks!

**Comment by vincss** [comment]
Hi !
This piece of software heavily depends on the npm package : https://www.npmjs.com/package/minecraft-protocol
They didn't release a new official version, however their repo contains a fix for this issue, so I updated with a ref to their repo.

Can you pull the latest version and try it ?

**Comment by Jefferderp** [comment]
Works great!

Thanks to c66e6fa (and thanks for mentioning the `npm install`) the server version is now reported correctly to the in-game server list.

Much appreciated :)

**Comment by vincss** [comment]
My pleasure ! :-) Have a nice game. ;-)
