### ISSUE TITLE
Cant use custom java location for starting the server

### ISSUE THREAD

**Issue by NewAmazingPVP** [vincss/mcsleepingserverstarter#91]
Generally in a server run.bat file you can specify what java the server uses. For example if you want to specify that your server uses java 17 then you can write "D:\Program Files\Java\jdk-17.0.2\bin\java.exe" -Xms2048m -Xmx4096m -jar paper-1.8.8-443.jar nogui  in the .bat file you use to start the server so then the server uses java 17.0.2 even if you system's java version is something else. This is good when you have multiple java versions installed on your pc and want to use different java versions for each server. But sadly this doesn't seem to work with mcsleepingserverstarter-win.exe. I have these settings:
serverName: SleepingServer, waiting for his prince...
serverPort: 25577
bedrockPort: 19132
maxPlayers: 20
loginMessage: ...Waking server up, come back in a minute...
serverOnlineMode: false
webPort: 0
startMinecraft: 1
minecraftCommand: "D:\Program Files\Java\jdk-17.0.2\bin\java.exe" -Xms2048m -Xmx4096m -jar paper-1.8.8-443.jar nogui
And when I try to run mcsleepingserverstarter it just reverts the default settings saying it failed to use the settings. I even tried running it in administrator mode but it still didn't work. I hope this feature can be somehow added? Thanks for your help in advance.
Also I really appreciate you for making this project. This project along with emptyserverstopper project allowed me to make a pretty big bungeecord instance that I can run without making my pc lag and allow my friends to join mulitiple servers without having to turn on/off the servers everytime. Thank you!

**Comment by vincss** [comment]
Hi,
I don't have a computer to try to reproduce for now, you don't have an error in the logs ? Maybe try with quotes arround the exécutable and args
"\"D:\Program Files\Java\jdk-17.0.2\bin\java.exe\" -Xms2048m -Xmx4096m -jar paper-1.8.8-443.jar nogui"

**Comment by NewAmazingPVP** [comment]
Also her is the server sleeper logs. https://pastebin.com/U6F4SGah Its pretty big I think you will just have to check the latest logs which are at the bottom.

**Comment by vincss** [comment]
Hi again, 
There was in fact an escape caractere issue, \ should be escaped with \\ : 
`
serverName: "SleepingServer, waiting for his prince..."
serverPort: 25577
bedrockPort: 19132
maxPlayers: 20
loginMessage: "...Waking server up, come back in a minute..."
serverOnlineMode: false
webPort: 0
startMinecraft: 1
minecraftCommand: "\"D:\\Program Files\\Java\\jdk-17.0.2\\bin\\java.exe\" -Xms2048m -Xmx4096m -jar paper-1.8.8-443.jar nogui"
`

**Comment by NewAmazingPVP** [comment]
OMG thanks it actually works now. I just didn't knew you had to use "\"D:\\Program Files\\Java\\jdk-17.0.2\\bin\\java.exe\" instead to choose the custom location. But now its fixed so thank you for your help I appreciate it!

**Comment by NewAmazingPVP** [comment]
Cool ill install the latest version. Also want to thank you for just making this amazing project. Keep going man
