### ISSUE TITLE
Can't install McSleeping on Zorin Os

### ISSUE THREAD

**Issue by Fufek-git** [vincss/mcsleepingserverstarter#93]
in zorin os, executable file has no extension so i cannot install it command "chmod +x mcsleepingserverstarter-linux" dosent work because in cmd it do completely nothing 
sorry but i am a beginner  and with manual install there is no file named npm install or any executable file

**Comment by Fufek-git** [comment]
but on windows it works completely fine

**Comment by vincss** [comment]
Hi !
Did you try with "./mcsleepingserverstarter-linux" ?
