### ISSUE TITLE
Way to do this outside of your wifi

### ISSUE THREAD

**Issue by r4Ph13** [vincss/mcsleepingserverstarter#94]
Hi is there a way to make this usable for people outside my wifi? Once the server starts my friends are able to join but if they try and join when the server is sleeping the server doesnt start up. I think its something relating to the web port but im not sure.

**Comment by r4Ph13** [comment]
Right now for people outside of my wifi it says "cant connect to server" when the server is sleeping

**Comment by vincss** [comment]
You must have a firewall issue, port forwarding issue or something like this.

**Comment by r4Ph13** [comment]
Do i need to change the web port to not a 0 or is it just an issue with my firewall/port forwarding

**Comment by iwa** [comment]
hello, you can already do that but you need to learn by yourself how to open ports on your router, forward ports to your marchine, configure firewall on your marchine, and maybe setup a ddns if needed
there are plenty of tutorials on the internet for that, just need to do a bit of searching

this does not rely on our program and is not a real issue

**Comment by vincss** [comment]
You don't need the webPort, it's for the web-gui only.
Did you checked the readme ? 
https://github.com/vincss/mcsleepingserverstarter#%EF%B8%8F-settings

**Comment by r4Ph13** [comment]
Oh ok. I think it was relating to the firewall because Node.js was being blocked by the firewall.

**Comment by r4Ph13** [comment]
> there are plenty of tutorials on the internet for that, just need to do a bit o

Yea i port forwarded and it works when the server is actaully running

**Comment by r4Ph13** [comment]
> You don't need the webPort, it's for the web-gui only. Did you checked the readme ? https://github.com/vincss/mcsleepingserverstarter#%EF%B8%8F-settings

oh ok
