### ISSUE TITLE
Multiple Versions? (ViaVersion)

### ISSUE THREAD

**Issue by Fufek-git** [vincss/mcsleepingserverstarter#95]
i just wanted to set more than one version cause my server has via version Do anyone know how to do that?

**Comment by vincss** [comment]
You can specify a version in the settings but you cannot setup multiple.
If you don't specify it, it will be compatible with the latest versions.

**Comment by sebasdt** [comment]
> i just wanted to set more than one version cause my server has via version Do anyone know how to do that?

you can enable the webpage to startup your server. That requires more security and trouble.
