### ISSUE TITLE
How do I make it start a minecraft docker container?

### ISSUE THREAD

**Issue by defning** [vincss/mcsleepingserverstarter#98]
my minecraft server is running on a [Docker Container](https://hub.docker.com/r/marctv/minecraft-papermc-server). How do I start the container instead of executing the server.jar file. Is it just easy as changing the minecraftcommand in the settings to `minecraftCommand: docker-compose up -d --build`? im running the server on a ubuntu server btw

**Comment by vincss** [comment]
Hi !
Can you put your solution is someone else is having the same issue ?

**Comment by sepiisagun** [comment]
@defning Hello, I know this issue has been closed already but would it be fine if you share your solution on how you made it work? I'm also trying to run this plugin with the same paper mc docker image but I'm having a hard time making it work since I'm still new on docker.
